
package org.tmforum.mtop.mri.wsdl.eir.v1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:24.546+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class EquipmentInventoryRetrievalRPC_EquipmentInventoryRetrievalRPC_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmforum.org/mtop/mri/wsdl/eir/v1-0", "EquipmentInventoryRetrievalHttp");

    private EquipmentInventoryRetrievalRPC_EquipmentInventoryRetrievalRPC_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EquipmentInventoryRetrievalHttp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EquipmentInventoryRetrievalHttp ss = new EquipmentInventoryRetrievalHttp(wsdlURL, SERVICE_NAME);
        EquipmentInventoryRetrievalRPC port = ss.getEquipmentInventoryRetrievalRPC();  
        
        {
        System.out.println("Invoking getContainedEquipment...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getContainedEquipment_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getContainedEquipment_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getContainedEquipment_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.eir.v1.GetContainedEquipmentRequest _getContainedEquipment_mtopBody = null;
        try {
            org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType _getContainedEquipment__return = port.getContainedEquipment(_getContainedEquipment_mtopHeader, _getContainedEquipment_mtopBody);
            System.out.println("getContainedEquipment.result=" + _getContainedEquipment__return);

            System.out.println("getContainedEquipment._getContainedEquipment_mtopHeader=" + _getContainedEquipment_mtopHeader.value);
        } catch (GetContainedEquipmentException e) { 
            System.out.println("Expected exception: GetContainedEquipmentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEquipment...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getEquipment_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getEquipment_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getEquipment_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentRequest _getEquipment_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentResponse _getEquipment__return = port.getEquipment(_getEquipment_mtopHeader, _getEquipment_mtopBody);
            System.out.println("getEquipment.result=" + _getEquipment__return);

            System.out.println("getEquipment._getEquipment_mtopHeader=" + _getEquipment_mtopHeader.value);
        } catch (GetEquipmentException e) { 
            System.out.println("Expected exception: GetEquipmentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllSupportingEquipment...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllSupportingEquipment_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllSupportingEquipment_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllSupportingEquipment_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentWithPtpRequestType _getAllSupportingEquipment_mtopBody = null;
        try {
            org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType _getAllSupportingEquipment__return = port.getAllSupportingEquipment(_getAllSupportingEquipment_mtopHeader, _getAllSupportingEquipment_mtopBody);
            System.out.println("getAllSupportingEquipment.result=" + _getAllSupportingEquipment__return);

            System.out.println("getAllSupportingEquipment._getAllSupportingEquipment_mtopHeader=" + _getAllSupportingEquipment_mtopHeader.value);
        } catch (GetAllSupportingEquipmentException e) { 
            System.out.println("Expected exception: GetAllSupportingEquipmentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSupportingEquipment...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getSupportingEquipment_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getSupportingEquipment_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getSupportingEquipment_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.eir.v1.GetSupportEquipmentRequestType _getSupportingEquipment_mtopBody = null;
        try {
            org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType _getSupportingEquipment__return = port.getSupportingEquipment(_getSupportingEquipment_mtopHeader, _getSupportingEquipment_mtopBody);
            System.out.println("getSupportingEquipment.result=" + _getSupportingEquipment__return);

            System.out.println("getSupportingEquipment._getSupportingEquipment_mtopHeader=" + _getSupportingEquipment_mtopHeader.value);
        } catch (GetSupportingEquipmentException e) { 
            System.out.println("Expected exception: GetSupportingEquipmentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSupportedEquipment...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getSupportedEquipment_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getSupportedEquipment_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getSupportedEquipment_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.eir.v1.GetSupportEquipmentRequestType _getSupportedEquipment_mtopBody = null;
        try {
            org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType _getSupportedEquipment__return = port.getSupportedEquipment(_getSupportedEquipment_mtopHeader, _getSupportedEquipment_mtopBody);
            System.out.println("getSupportedEquipment.result=" + _getSupportedEquipment__return);

            System.out.println("getSupportedEquipment._getSupportedEquipment_mtopHeader=" + _getSupportedEquipment_mtopHeader.value);
        } catch (GetSupportedEquipmentException e) { 
            System.out.println("Expected exception: GetSupportedEquipmentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getEquipmentIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getEquipmentIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getEquipmentIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getEquipmentIterator_mtopHeaderVal);
        java.lang.Object _getEquipmentIterator_mtopBody = new java.lang.Object();
        try {
            org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType _getEquipmentIterator__return = port.getEquipmentIterator(_getEquipmentIterator_mtopHeader, _getEquipmentIterator_mtopBody);
            System.out.println("getEquipmentIterator.result=" + _getEquipmentIterator__return);

            System.out.println("getEquipmentIterator._getEquipmentIterator_mtopHeader=" + _getEquipmentIterator_mtopHeader.value);
        } catch (GetEquipmentIteratorException e) { 
            System.out.println("Expected exception: GetEquipmentIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllEquipment...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllEquipment_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllEquipment_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllEquipment_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentRequestType _getAllEquipment_mtopBody = null;
        try {
            org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType _getAllEquipment__return = port.getAllEquipment(_getAllEquipment_mtopHeader, _getAllEquipment_mtopBody);
            System.out.println("getAllEquipment.result=" + _getAllEquipment__return);

            System.out.println("getAllEquipment._getAllEquipment_mtopHeader=" + _getAllEquipment_mtopHeader.value);
        } catch (GetAllEquipmentException e) { 
            System.out.println("Expected exception: GetAllEquipmentException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
