package org.tmforum.mtop.mri.wsdl.eir.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:24.859+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.tmforum.org/mtop/mri/wsdl/eir/v1-0", name = "EquipmentInventoryRetrieval_RPC")
@XmlSeeAlso({org.tmforum.mtop.nrf.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.hdr.v1.ObjectFactory.class, org.tmforum.mtop.vs.xsd.rr.v1.ObjectFactory.class, org.tmforum.mtop.mri.xsd.eir.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lay.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.tnp.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.coi.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.msg.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.gen.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.cri.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.tpdata.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.eh.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.nam.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pgp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lp.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.eq.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.eq_inv.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EquipmentInventoryRetrievalRPC {

    @WebResult(name = "getContainedEquipmentResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getContainedEquipment")
    public org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType getContainedEquipment(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getContainedEquipmentRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        org.tmforum.mtop.mri.xsd.eir.v1.GetContainedEquipmentRequest mtopBody
    ) throws GetContainedEquipmentException;

    @WebResult(name = "getEquipmentResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getEquipment")
    public org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentResponse getEquipment(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getEquipmentRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentRequest mtopBody
    ) throws GetEquipmentException;

    @WebResult(name = "getAllSupportingEquipmentResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getAllSupportingEquipment")
    public org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType getAllSupportingEquipment(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllSupportingEquipmentRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentWithPtpRequestType mtopBody
    ) throws GetAllSupportingEquipmentException;

    @WebResult(name = "getSupportingEquipmentResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getSupportingEquipment")
    public org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType getSupportingEquipment(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getSupportingEquipmentRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        org.tmforum.mtop.mri.xsd.eir.v1.GetSupportEquipmentRequestType mtopBody
    ) throws GetSupportingEquipmentException;

    @WebResult(name = "getSupportedEquipmentResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getSupportedEquipment")
    public org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType getSupportedEquipment(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getSupportedEquipmentRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        org.tmforum.mtop.mri.xsd.eir.v1.GetSupportEquipmentRequestType mtopBody
    ) throws GetSupportedEquipmentException;

    @WebResult(name = "getEquipmentIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getEquipmentIterator")
    public org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType getEquipmentIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getEquipmentIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        java.lang.Object mtopBody
    ) throws GetEquipmentIteratorException;

    @WebResult(name = "getAllEquipmentResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1", partName = "mtopBody")
    @WebMethod(action = "getAllEquipment")
    public org.tmforum.mtop.nrf.xsd.eq_inv.v1.EquipmentOrEquipmentHolderListType getAllEquipment(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllEquipmentRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
        org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentRequestType mtopBody
    ) throws GetAllEquipmentException;
}
