
package org.tmforum.mtop.mri.wsdl.eir.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:24.843+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllEquipmentException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
public class GetAllEquipmentException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentException getAllEquipmentException;

    public GetAllEquipmentException() {
        super();
    }
    
    public GetAllEquipmentException(String message) {
        super(message);
    }
    
    public GetAllEquipmentException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllEquipmentException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentException getAllEquipmentException) {
        super(message);
        this.getAllEquipmentException = getAllEquipmentException;
    }

    public GetAllEquipmentException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentException getAllEquipmentException, Throwable cause) {
        super(message, cause);
        this.getAllEquipmentException = getAllEquipmentException;
    }

    public org.tmforum.mtop.mri.xsd.eir.v1.GetAllEquipmentException getFaultInfo() {
        return this.getAllEquipmentException;
    }
}
