
package org.tmforum.mtop.mri.wsdl.eir.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:24.765+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllSupportingEquipmentException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
public class GetAllSupportingEquipmentException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.eir.v1.GetAllSupportingEquipmentException getAllSupportingEquipmentException;

    public GetAllSupportingEquipmentException() {
        super();
    }
    
    public GetAllSupportingEquipmentException(String message) {
        super(message);
    }
    
    public GetAllSupportingEquipmentException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllSupportingEquipmentException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetAllSupportingEquipmentException getAllSupportingEquipmentException) {
        super(message);
        this.getAllSupportingEquipmentException = getAllSupportingEquipmentException;
    }

    public GetAllSupportingEquipmentException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetAllSupportingEquipmentException getAllSupportingEquipmentException, Throwable cause) {
        super(message, cause);
        this.getAllSupportingEquipmentException = getAllSupportingEquipmentException;
    }

    public org.tmforum.mtop.mri.xsd.eir.v1.GetAllSupportingEquipmentException getFaultInfo() {
        return this.getAllSupportingEquipmentException;
    }
}
