
package org.tmforum.mtop.mri.wsdl.eir.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:24.765+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getEquipmentException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
public class GetEquipmentException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentException getEquipmentException;

    public GetEquipmentException() {
        super();
    }
    
    public GetEquipmentException(String message) {
        super(message);
    }
    
    public GetEquipmentException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetEquipmentException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentException getEquipmentException) {
        super(message);
        this.getEquipmentException = getEquipmentException;
    }

    public GetEquipmentException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentException getEquipmentException, Throwable cause) {
        super(message, cause);
        this.getEquipmentException = getEquipmentException;
    }

    public org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentException getFaultInfo() {
        return this.getEquipmentException;
    }
}
