
package org.tmforum.mtop.mri.wsdl.eir.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:24.828+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getEquipmentIteratorException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/eir/v1")
public class GetEquipmentIteratorException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentIteratorException getEquipmentIteratorException;

    public GetEquipmentIteratorException() {
        super();
    }
    
    public GetEquipmentIteratorException(String message) {
        super(message);
    }
    
    public GetEquipmentIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetEquipmentIteratorException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentIteratorException getEquipmentIteratorException) {
        super(message);
        this.getEquipmentIteratorException = getEquipmentIteratorException;
    }

    public GetEquipmentIteratorException(String message, org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentIteratorException getEquipmentIteratorException, Throwable cause) {
        super(message, cause);
        this.getEquipmentIteratorException = getEquipmentIteratorException;
    }

    public org.tmforum.mtop.mri.xsd.eir.v1.GetEquipmentIteratorException getFaultInfo() {
        return this.getEquipmentIteratorException;
    }
}
