
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.781+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllManagedElementInfosByIPsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/dusr/v1")
public class GetAllManagedElementInfosByIPsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsException getAllManagedElementInfosByIPsException;

    public GetAllManagedElementInfosByIPsException() {
        super();
    }
    
    public GetAllManagedElementInfosByIPsException(String message) {
        super(message);
    }
    
    public GetAllManagedElementInfosByIPsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllManagedElementInfosByIPsException(String message, org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsException getAllManagedElementInfosByIPsException) {
        super(message);
        this.getAllManagedElementInfosByIPsException = getAllManagedElementInfosByIPsException;
    }

    public GetAllManagedElementInfosByIPsException(String message, org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsException getAllManagedElementInfosByIPsException, Throwable cause) {
        super(message, cause);
        this.getAllManagedElementInfosByIPsException = getAllManagedElementInfosByIPsException;
    }

    public org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsException getFaultInfo() {
        return this.getAllManagedElementInfosByIPsException;
    }
}
