
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.640+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllManagedElementsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetAllManagedElementsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsException getAllManagedElementsException;

    public GetAllManagedElementsException() {
        super();
    }
    
    public GetAllManagedElementsException(String message) {
        super(message);
    }
    
    public GetAllManagedElementsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllManagedElementsException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsException getAllManagedElementsException) {
        super(message);
        this.getAllManagedElementsException = getAllManagedElementsException;
    }

    public GetAllManagedElementsException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsException getAllManagedElementsException, Throwable cause) {
        super(message, cause);
        this.getAllManagedElementsException = getAllManagedElementsException;
    }

    public org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsException getFaultInfo() {
        return this.getAllManagedElementsException;
    }
}
