
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.812+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllManagedElementNamesException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetAllManagedElementNamesException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementNamesException getAllManagedElementNamesException;

    public GetAllManagedElementNamesException() {
        super();
    }
    
    public GetAllManagedElementNamesException(String message) {
        super(message);
    }
    
    public GetAllManagedElementNamesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllManagedElementNamesException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementNamesException getAllManagedElementNamesException) {
        super(message);
        this.getAllManagedElementNamesException = getAllManagedElementNamesException;
    }

    public GetAllManagedElementNamesException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementNamesException getAllManagedElementNamesException, Throwable cause) {
        super(message, cause);
        this.getAllManagedElementNamesException = getAllManagedElementNamesException;
    }

    public org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementNamesException getFaultInfo() {
        return this.getAllManagedElementNamesException;
    }
}
