
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.703+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllManagedElementsWrtOsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetAllManagedElementsWrtOsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsWrtOsException getAllManagedElementsWrtOsException;

    public GetAllManagedElementsWrtOsException() {
        super();
    }
    
    public GetAllManagedElementsWrtOsException(String message) {
        super(message);
    }
    
    public GetAllManagedElementsWrtOsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllManagedElementsWrtOsException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsWrtOsException getAllManagedElementsWrtOsException) {
        super(message);
        this.getAllManagedElementsWrtOsException = getAllManagedElementsWrtOsException;
    }

    public GetAllManagedElementsWrtOsException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsWrtOsException getAllManagedElementsWrtOsException, Throwable cause) {
        super(message, cause);
        this.getAllManagedElementsWrtOsException = getAllManagedElementsWrtOsException;
    }

    public org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsWrtOsException getFaultInfo() {
        return this.getAllManagedElementsWrtOsException;
    }
}
