
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.703+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllManagedElementsPassingFilterException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetAllManagedElementsPassingFilterException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsPassingFilterException getAllManagedElementsPassingFilterException;

    public GetAllManagedElementsPassingFilterException() {
        super();
    }
    
    public GetAllManagedElementsPassingFilterException(String message) {
        super(message);
    }
    
    public GetAllManagedElementsPassingFilterException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllManagedElementsPassingFilterException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsPassingFilterException getAllManagedElementsPassingFilterException) {
        super(message);
        this.getAllManagedElementsPassingFilterException = getAllManagedElementsPassingFilterException;
    }

    public GetAllManagedElementsPassingFilterException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsPassingFilterException getAllManagedElementsPassingFilterException, Throwable cause) {
        super(message, cause);
        this.getAllManagedElementsPassingFilterException = getAllManagedElementsPassingFilterException;
    }

    public org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsPassingFilterException getFaultInfo() {
        return this.getAllManagedElementsPassingFilterException;
    }
}
