
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.734+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getManagedElementsIteratorException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetManagedElementsIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getManagedElementsIteratorException;

    public GetManagedElementsIteratorException() {
        super();
    }
    
    public GetManagedElementsIteratorException(String message) {
        super(message);
    }
    
    public GetManagedElementsIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetManagedElementsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getManagedElementsIteratorException) {
        super(message);
        this.getManagedElementsIteratorException = getManagedElementsIteratorException;
    }

    public GetManagedElementsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getManagedElementsIteratorException, Throwable cause) {
        super(message, cause);
        this.getManagedElementsIteratorException = getManagedElementsIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getManagedElementsIteratorException;
    }
}
