
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.796+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getManagedElementException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetManagedElementException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.mer.v1.GetManagedElementException getManagedElementException;

    public GetManagedElementException() {
        super();
    }
    
    public GetManagedElementException(String message) {
        super(message);
    }
    
    public GetManagedElementException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetManagedElementException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetManagedElementException getManagedElementException) {
        super(message);
        this.getManagedElementException = getManagedElementException;
    }

    public GetManagedElementException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetManagedElementException getManagedElementException, Throwable cause) {
        super(message, cause);
        this.getManagedElementException = getManagedElementException;
    }

    public org.tmforum.mtop.mri.xsd.mer.v1.GetManagedElementException getFaultInfo() {
        return this.getManagedElementException;
    }
}
