
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.796+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getSubtendingManagedElementsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
public class GetSubtendingManagedElementsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.mer.v1.GetSubtendingManagedElementsException getSubtendingManagedElementsException;

    public GetSubtendingManagedElementsException() {
        super();
    }
    
    public GetSubtendingManagedElementsException(String message) {
        super(message);
    }
    
    public GetSubtendingManagedElementsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetSubtendingManagedElementsException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetSubtendingManagedElementsException getSubtendingManagedElementsException) {
        super(message);
        this.getSubtendingManagedElementsException = getSubtendingManagedElementsException;
    }

    public GetSubtendingManagedElementsException(String message, org.tmforum.mtop.mri.xsd.mer.v1.GetSubtendingManagedElementsException getSubtendingManagedElementsException, Throwable cause) {
        super(message, cause);
        this.getSubtendingManagedElementsException = getSubtendingManagedElementsException;
    }

    public org.tmforum.mtop.mri.xsd.mer.v1.GetSubtendingManagedElementsException getFaultInfo() {
        return this.getSubtendingManagedElementsException;
    }
}
