package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.828+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.tmforum.org/mtop/mri/wsdl/mer/v1-0", name = "ManagedElementRetrieval_RPC")
@XmlSeeAlso({org.tmforum.mtop.fmw.xsd.hdr.v1.ObjectFactory.class, org.tmforum.mtop.vs.xsd.rr.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lay.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.tnp.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.coi.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.msg.v1.ObjectFactory.class, org.tmforum.mtop.mri.xsd.mer.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.gen.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.me.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.cri.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.nam.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pgp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.mri.xsd.dusr.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManagedElementRetrievalRPC {

    @WebResult(name = "getAllManagedElementsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getAllManagedElements")
    public org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType getAllManagedElements(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllManagedElementsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsRequest mtopBody
    ) throws GetAllManagedElementsException;

    @WebResult(name = "getAllManagedElementsWrtOsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getAllManagedElementsWrtOs")
    public org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType getAllManagedElementsWrtOs(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllManagedElementsWrtOsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsWrtOsRequest mtopBody
    ) throws GetAllManagedElementsWrtOsException;

    @WebResult(name = "getAllManagedElementsPassingFilterResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getAllManagedElementsPassingFilter")
    public org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType getAllManagedElementsPassingFilter(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllManagedElementsPassingFilterRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsPassingFilterRequest mtopBody
    ) throws GetAllManagedElementsPassingFilterException;

    @WebResult(name = "getManagedElementsIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getManagedElementsIterator")
    public org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType getManagedElementsIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getManagedElementsIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetManagedElementsIteratorException;

    @WebResult(name = "getManagedElementNamesIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getManagedElementNamesIterator")
    public org.tmforum.mtop.fmw.xsd.nam.v1.NamingAttributeListType getManagedElementNamesIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getManagedElementNamesIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetManagedElementNamesIteratorException;

    @WebResult(name = "getAllManagedElementInfosByIPsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/dusr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllManagedElementInfosByIPs")
    public org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsResponse getAllManagedElementInfosByIPs(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllManagedElementInfosByIPsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/dusr/v1")
        org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsRequest mtopBody
    ) throws GetAllManagedElementInfosByIPsException;

    @WebResult(name = "getManagedElementResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getManagedElement")
    public org.tmforum.mtop.mri.xsd.mer.v1.SingleMeObjectResponseType getManagedElement(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getManagedElementRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.mri.xsd.mer.v1.GetManagedElementRequest mtopBody
    ) throws GetManagedElementException;

    @WebResult(name = "getSubtendingManagedElementsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getSubtendingManagedElements")
    public org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType getSubtendingManagedElements(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getSubtendingManagedElementsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.mri.xsd.mer.v1.GetSubtendingManagedElementsRequest mtopBody
    ) throws GetSubtendingManagedElementsException;

    @WebResult(name = "getAllManagedElementNamesResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", partName = "mtopBody")
    @WebMethod(action = "getAllManagedElementNames")
    public org.tmforum.mtop.fmw.xsd.nam.v1.NamingAttributeListType getAllManagedElementNames(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllManagedElementNamesRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1")
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementNamesRequest mtopBody
    ) throws GetAllManagedElementNamesException;
}
