
package org.tmforum.mtop.mri.wsdl.mer.v1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.484+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class ManagedElementRetrievalRPC_ManagedElementRetrievalRPC_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmforum.org/mtop/mri/wsdl/mer/v1-0", "ManagedElementRetrievalHttp");

    private ManagedElementRetrievalRPC_ManagedElementRetrievalRPC_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ManagedElementRetrievalHttp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ManagedElementRetrievalHttp ss = new ManagedElementRetrievalHttp(wsdlURL, SERVICE_NAME);
        ManagedElementRetrievalRPC port = ss.getManagedElementRetrievalRPC();  
        
        {
        System.out.println("Invoking getAllManagedElements...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllManagedElements_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllManagedElements_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllManagedElements_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsRequest _getAllManagedElements_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType _getAllManagedElements__return = port.getAllManagedElements(_getAllManagedElements_mtopHeader, _getAllManagedElements_mtopBody);
            System.out.println("getAllManagedElements.result=" + _getAllManagedElements__return);

            System.out.println("getAllManagedElements._getAllManagedElements_mtopHeader=" + _getAllManagedElements_mtopHeader.value);
        } catch (GetAllManagedElementsException e) { 
            System.out.println("Expected exception: GetAllManagedElementsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllManagedElementsWrtOs...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllManagedElementsWrtOs_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllManagedElementsWrtOs_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllManagedElementsWrtOs_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsWrtOsRequest _getAllManagedElementsWrtOs_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType _getAllManagedElementsWrtOs__return = port.getAllManagedElementsWrtOs(_getAllManagedElementsWrtOs_mtopHeader, _getAllManagedElementsWrtOs_mtopBody);
            System.out.println("getAllManagedElementsWrtOs.result=" + _getAllManagedElementsWrtOs__return);

            System.out.println("getAllManagedElementsWrtOs._getAllManagedElementsWrtOs_mtopHeader=" + _getAllManagedElementsWrtOs_mtopHeader.value);
        } catch (GetAllManagedElementsWrtOsException e) { 
            System.out.println("Expected exception: GetAllManagedElementsWrtOsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllManagedElementsPassingFilter...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllManagedElementsPassingFilter_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllManagedElementsPassingFilter_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllManagedElementsPassingFilter_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementsPassingFilterRequest _getAllManagedElementsPassingFilter_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType _getAllManagedElementsPassingFilter__return = port.getAllManagedElementsPassingFilter(_getAllManagedElementsPassingFilter_mtopHeader, _getAllManagedElementsPassingFilter_mtopBody);
            System.out.println("getAllManagedElementsPassingFilter.result=" + _getAllManagedElementsPassingFilter__return);

            System.out.println("getAllManagedElementsPassingFilter._getAllManagedElementsPassingFilter_mtopHeader=" + _getAllManagedElementsPassingFilter_mtopHeader.value);
        } catch (GetAllManagedElementsPassingFilterException e) { 
            System.out.println("Expected exception: GetAllManagedElementsPassingFilterException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getManagedElementsIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getManagedElementsIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getManagedElementsIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getManagedElementsIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getManagedElementsIterator_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType _getManagedElementsIterator__return = port.getManagedElementsIterator(_getManagedElementsIterator_mtopHeader, _getManagedElementsIterator_mtopBody);
            System.out.println("getManagedElementsIterator.result=" + _getManagedElementsIterator__return);

            System.out.println("getManagedElementsIterator._getManagedElementsIterator_mtopHeader=" + _getManagedElementsIterator_mtopHeader.value);
        } catch (GetManagedElementsIteratorException e) { 
            System.out.println("Expected exception: GetManagedElementsIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getManagedElementNamesIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getManagedElementNamesIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getManagedElementNamesIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getManagedElementNamesIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getManagedElementNamesIterator_mtopBody = null;
        try {
            org.tmforum.mtop.fmw.xsd.nam.v1.NamingAttributeListType _getManagedElementNamesIterator__return = port.getManagedElementNamesIterator(_getManagedElementNamesIterator_mtopHeader, _getManagedElementNamesIterator_mtopBody);
            System.out.println("getManagedElementNamesIterator.result=" + _getManagedElementNamesIterator__return);

            System.out.println("getManagedElementNamesIterator._getManagedElementNamesIterator_mtopHeader=" + _getManagedElementNamesIterator_mtopHeader.value);
        } catch (GetManagedElementNamesIteratorException e) { 
            System.out.println("Expected exception: GetManagedElementNamesIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllManagedElementInfosByIPs...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllManagedElementInfosByIPs_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllManagedElementInfosByIPs_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllManagedElementInfosByIPs_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsRequest _getAllManagedElementInfosByIPs_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.dusr.v1.GetAllManagedElementInfosByIPsResponse _getAllManagedElementInfosByIPs__return = port.getAllManagedElementInfosByIPs(_getAllManagedElementInfosByIPs_mtopHeader, _getAllManagedElementInfosByIPs_mtopBody);
            System.out.println("getAllManagedElementInfosByIPs.result=" + _getAllManagedElementInfosByIPs__return);

            System.out.println("getAllManagedElementInfosByIPs._getAllManagedElementInfosByIPs_mtopHeader=" + _getAllManagedElementInfosByIPs_mtopHeader.value);
        } catch (GetAllManagedElementInfosByIPsException e) { 
            System.out.println("Expected exception: GetAllManagedElementInfosByIPsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getManagedElement...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getManagedElement_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getManagedElement_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getManagedElement_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.mer.v1.GetManagedElementRequest _getManagedElement_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.mer.v1.SingleMeObjectResponseType _getManagedElement__return = port.getManagedElement(_getManagedElement_mtopHeader, _getManagedElement_mtopBody);
            System.out.println("getManagedElement.result=" + _getManagedElement__return);

            System.out.println("getManagedElement._getManagedElement_mtopHeader=" + _getManagedElement_mtopHeader.value);
        } catch (GetManagedElementException e) { 
            System.out.println("Expected exception: GetManagedElementException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSubtendingManagedElements...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getSubtendingManagedElements_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getSubtendingManagedElements_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getSubtendingManagedElements_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.mer.v1.GetSubtendingManagedElementsRequest _getSubtendingManagedElements_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.mer.v1.MultipleMeObjectsResponseType _getSubtendingManagedElements__return = port.getSubtendingManagedElements(_getSubtendingManagedElements_mtopHeader, _getSubtendingManagedElements_mtopBody);
            System.out.println("getSubtendingManagedElements.result=" + _getSubtendingManagedElements__return);

            System.out.println("getSubtendingManagedElements._getSubtendingManagedElements_mtopHeader=" + _getSubtendingManagedElements_mtopHeader.value);
        } catch (GetSubtendingManagedElementsException e) { 
            System.out.println("Expected exception: GetSubtendingManagedElementsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllManagedElementNames...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllManagedElementNames_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllManagedElementNames_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllManagedElementNames_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.mer.v1.GetAllManagedElementNamesRequest _getAllManagedElementNames_mtopBody = null;
        try {
            org.tmforum.mtop.fmw.xsd.nam.v1.NamingAttributeListType _getAllManagedElementNames__return = port.getAllManagedElementNames(_getAllManagedElementNames_mtopHeader, _getAllManagedElementNames_mtopBody);
            System.out.println("getAllManagedElementNames.result=" + _getAllManagedElementNames__return);

            System.out.println("getAllManagedElementNames._getAllManagedElementNames_mtopHeader=" + _getAllManagedElementNames_mtopHeader.value);
        } catch (GetAllManagedElementNamesException e) { 
            System.out.println("Expected exception: GetAllManagedElementNamesException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
