package org.tmforum.mtop.mri.wsdl.mer.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:10.843+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "ManagedElementRetrievalHttp", 
                  wsdlLocation = "http://192.168.189.46:9997/ManagedElementRetrieval?wsdl",
                  targetNamespace = "http://www.tmforum.org/mtop/mri/wsdl/mer/v1-0") 
public class ManagedElementRetrievalHttp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmforum.org/mtop/mri/wsdl/mer/v1-0", "ManagedElementRetrievalHttp");
    public final static QName ManagedElementRetrievalRPC = new QName("http://www.tmforum.org/mtop/mri/wsdl/mer/v1-0", "ManagedElementRetrieval_RPC");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.189.46:9997/ManagedElementRetrieval?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManagedElementRetrievalHttp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.189.46:9997/ManagedElementRetrieval?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManagedElementRetrievalHttp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManagedElementRetrievalHttp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagedElementRetrievalHttp() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ManagedElementRetrievalRPC
     */
    @WebEndpoint(name = "ManagedElementRetrieval_RPC")
    public ManagedElementRetrievalRPC getManagedElementRetrievalRPC() {
        return super.getPort(ManagedElementRetrievalRPC, ManagedElementRetrievalRPC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagedElementRetrievalRPC
     */
    @WebEndpoint(name = "ManagedElementRetrieval_RPC")
    public ManagedElementRetrievalRPC getManagedElementRetrievalRPC(WebServiceFeature... features) {
        return super.getPort(ManagedElementRetrievalRPC, ManagedElementRetrievalRPC.class, features);
    }

}
