
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.906+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllPhysicalTerminationPointsWithoutFtpsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAllPhysicalTerminationPointsWithoutFtpsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsWithoutFtpsException getAllPhysicalTerminationPointsWithoutFtpsException;

    public GetAllPhysicalTerminationPointsWithoutFtpsException() {
        super();
    }
    
    public GetAllPhysicalTerminationPointsWithoutFtpsException(String message) {
        super(message);
    }
    
    public GetAllPhysicalTerminationPointsWithoutFtpsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllPhysicalTerminationPointsWithoutFtpsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsWithoutFtpsException getAllPhysicalTerminationPointsWithoutFtpsException) {
        super(message);
        this.getAllPhysicalTerminationPointsWithoutFtpsException = getAllPhysicalTerminationPointsWithoutFtpsException;
    }

    public GetAllPhysicalTerminationPointsWithoutFtpsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsWithoutFtpsException getAllPhysicalTerminationPointsWithoutFtpsException, Throwable cause) {
        super(message, cause);
        this.getAllPhysicalTerminationPointsWithoutFtpsException = getAllPhysicalTerminationPointsWithoutFtpsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsWithoutFtpsException getFaultInfo() {
        return this.getAllPhysicalTerminationPointsWithoutFtpsException;
    }
}
