
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.515+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAssociatedTerminationPointException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAssociatedTerminationPointException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedTerminationPointException getAssociatedTerminationPointException;

    public GetAssociatedTerminationPointException() {
        super();
    }
    
    public GetAssociatedTerminationPointException(String message) {
        super(message);
    }
    
    public GetAssociatedTerminationPointException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAssociatedTerminationPointException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedTerminationPointException getAssociatedTerminationPointException) {
        super(message);
        this.getAssociatedTerminationPointException = getAssociatedTerminationPointException;
    }

    public GetAssociatedTerminationPointException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedTerminationPointException getAssociatedTerminationPointException, Throwable cause) {
        super(message, cause);
        this.getAssociatedTerminationPointException = getAssociatedTerminationPointException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedTerminationPointException getFaultInfo() {
        return this.getAssociatedTerminationPointException;
    }
}
