
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.953+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllFloatingTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAllFloatingTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAllFloatingTerminationPointsException getAllFloatingTerminationPointsException;

    public GetAllFloatingTerminationPointsException() {
        super();
    }
    
    public GetAllFloatingTerminationPointsException(String message) {
        super(message);
    }
    
    public GetAllFloatingTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllFloatingTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllFloatingTerminationPointsException getAllFloatingTerminationPointsException) {
        super(message);
        this.getAllFloatingTerminationPointsException = getAllFloatingTerminationPointsException;
    }

    public GetAllFloatingTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllFloatingTerminationPointsException getAllFloatingTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getAllFloatingTerminationPointsException = getAllFloatingTerminationPointsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllFloatingTerminationPointsException getFaultInfo() {
        return this.getAllFloatingTerminationPointsException;
    }
}
