
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.750+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAssociatedTerminationPointsWrtTmdException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAssociatedTerminationPointsWrtTmdException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile1Type getAssociatedTerminationPointsWrtTmdException;

    public GetAssociatedTerminationPointsWrtTmdException() {
        super();
    }
    
    public GetAssociatedTerminationPointsWrtTmdException(String message) {
        super(message);
    }
    
    public GetAssociatedTerminationPointsWrtTmdException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAssociatedTerminationPointsWrtTmdException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile1Type getAssociatedTerminationPointsWrtTmdException) {
        super(message);
        this.getAssociatedTerminationPointsWrtTmdException = getAssociatedTerminationPointsWrtTmdException;
    }

    public GetAssociatedTerminationPointsWrtTmdException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile1Type getAssociatedTerminationPointsWrtTmdException, Throwable cause) {
        super(message, cause);
        this.getAssociatedTerminationPointsWrtTmdException = getAssociatedTerminationPointsWrtTmdException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile1Type getFaultInfo() {
        return this.getAssociatedTerminationPointsWrtTmdException;
    }
}
