
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.765+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllSupportedPhysicalTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAllSupportedPhysicalTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAllSupportedPhysicalTerminationPointsException getAllSupportedPhysicalTerminationPointsException;

    public GetAllSupportedPhysicalTerminationPointsException() {
        super();
    }
    
    public GetAllSupportedPhysicalTerminationPointsException(String message) {
        super(message);
    }
    
    public GetAllSupportedPhysicalTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllSupportedPhysicalTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllSupportedPhysicalTerminationPointsException getAllSupportedPhysicalTerminationPointsException) {
        super(message);
        this.getAllSupportedPhysicalTerminationPointsException = getAllSupportedPhysicalTerminationPointsException;
    }

    public GetAllSupportedPhysicalTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllSupportedPhysicalTerminationPointsException getAllSupportedPhysicalTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getAllSupportedPhysicalTerminationPointsException = getAllSupportedPhysicalTerminationPointsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllSupportedPhysicalTerminationPointsException getFaultInfo() {
        return this.getAllSupportedPhysicalTerminationPointsException;
    }
}
