
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.718+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllTerminationPointPoolsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAllTerminationPointPoolsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointPoolsException getAllTerminationPointPoolsException;

    public GetAllTerminationPointPoolsException() {
        super();
    }
    
    public GetAllTerminationPointPoolsException(String message) {
        super(message);
    }
    
    public GetAllTerminationPointPoolsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllTerminationPointPoolsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointPoolsException getAllTerminationPointPoolsException) {
        super(message);
        this.getAllTerminationPointPoolsException = getAllTerminationPointPoolsException;
    }

    public GetAllTerminationPointPoolsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointPoolsException getAllTerminationPointPoolsException, Throwable cause) {
        super(message, cause);
        this.getAllTerminationPointPoolsException = getAllTerminationPointPoolsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointPoolsException getFaultInfo() {
        return this.getAllTerminationPointPoolsException;
    }
}
