
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.578+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllGroupTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAllGroupTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAllGroupTerminationPointsException getAllGroupTerminationPointsException;

    public GetAllGroupTerminationPointsException() {
        super();
    }
    
    public GetAllGroupTerminationPointsException(String message) {
        super(message);
    }
    
    public GetAllGroupTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllGroupTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllGroupTerminationPointsException getAllGroupTerminationPointsException) {
        super(message);
        this.getAllGroupTerminationPointsException = getAllGroupTerminationPointsException;
    }

    public GetAllGroupTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllGroupTerminationPointsException getAllGroupTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getAllGroupTerminationPointsException = getAllGroupTerminationPointsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllGroupTerminationPointsException getFaultInfo() {
        return this.getAllGroupTerminationPointsException;
    }
}
