
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.875+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllPhysicalTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetAllPhysicalTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsException getAllPhysicalTerminationPointsException;

    public GetAllPhysicalTerminationPointsException() {
        super();
    }
    
    public GetAllPhysicalTerminationPointsException(String message) {
        super(message);
    }
    
    public GetAllPhysicalTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllPhysicalTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsException getAllPhysicalTerminationPointsException) {
        super(message);
        this.getAllPhysicalTerminationPointsException = getAllPhysicalTerminationPointsException;
    }

    public GetAllPhysicalTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsException getAllPhysicalTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getAllPhysicalTerminationPointsException = getAllPhysicalTerminationPointsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointsException getFaultInfo() {
        return this.getAllPhysicalTerminationPointsException;
    }
}
