
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.687+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getContainedInUseConnectionTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetContainedInUseConnectionTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedInUseConnectionTerminationPointsException getContainedInUseConnectionTerminationPointsException;

    public GetContainedInUseConnectionTerminationPointsException() {
        super();
    }
    
    public GetContainedInUseConnectionTerminationPointsException(String message) {
        super(message);
    }
    
    public GetContainedInUseConnectionTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContainedInUseConnectionTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedInUseConnectionTerminationPointsException getContainedInUseConnectionTerminationPointsException) {
        super(message);
        this.getContainedInUseConnectionTerminationPointsException = getContainedInUseConnectionTerminationPointsException;
    }

    public GetContainedInUseConnectionTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedInUseConnectionTerminationPointsException getContainedInUseConnectionTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getContainedInUseConnectionTerminationPointsException = getContainedInUseConnectionTerminationPointsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedInUseConnectionTerminationPointsException getFaultInfo() {
        return this.getContainedInUseConnectionTerminationPointsException;
    }
}
