
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.375+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getContainedPotentialConnectionTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetContainedPotentialConnectionTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedPotentialConnectionTerminationPointsException getContainedPotentialConnectionTerminationPointsException;

    public GetContainedPotentialConnectionTerminationPointsException() {
        super();
    }
    
    public GetContainedPotentialConnectionTerminationPointsException(String message) {
        super(message);
    }
    
    public GetContainedPotentialConnectionTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContainedPotentialConnectionTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedPotentialConnectionTerminationPointsException getContainedPotentialConnectionTerminationPointsException) {
        super(message);
        this.getContainedPotentialConnectionTerminationPointsException = getContainedPotentialConnectionTerminationPointsException;
    }

    public GetContainedPotentialConnectionTerminationPointsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedPotentialConnectionTerminationPointsException getContainedPotentialConnectionTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getContainedPotentialConnectionTerminationPointsException = getContainedPotentialConnectionTerminationPointsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetContainedPotentialConnectionTerminationPointsException getFaultInfo() {
        return this.getContainedPotentialConnectionTerminationPointsException;
    }
}
