
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.796+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getGroupTerminationPointsIteratorException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetGroupTerminationPointsIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getGroupTerminationPointsIteratorException;

    public GetGroupTerminationPointsIteratorException() {
        super();
    }
    
    public GetGroupTerminationPointsIteratorException(String message) {
        super(message);
    }
    
    public GetGroupTerminationPointsIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetGroupTerminationPointsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getGroupTerminationPointsIteratorException) {
        super(message);
        this.getGroupTerminationPointsIteratorException = getGroupTerminationPointsIteratorException;
    }

    public GetGroupTerminationPointsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getGroupTerminationPointsIteratorException, Throwable cause) {
        super(message, cause);
        this.getGroupTerminationPointsIteratorException = getGroupTerminationPointsIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getGroupTerminationPointsIteratorException;
    }
}
