
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.421+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getGroupTerminationPointException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetGroupTerminationPointException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetGroupTerminationPointException getGroupTerminationPointException;

    public GetGroupTerminationPointException() {
        super();
    }
    
    public GetGroupTerminationPointException(String message) {
        super(message);
    }
    
    public GetGroupTerminationPointException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetGroupTerminationPointException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetGroupTerminationPointException getGroupTerminationPointException) {
        super(message);
        this.getGroupTerminationPointException = getGroupTerminationPointException;
    }

    public GetGroupTerminationPointException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetGroupTerminationPointException getGroupTerminationPointException, Throwable cause) {
        super(message, cause);
        this.getGroupTerminationPointException = getGroupTerminationPointException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetGroupTerminationPointException getFaultInfo() {
        return this.getGroupTerminationPointException;
    }
}
