
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.953+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTerminationPointGroupingRelationshipsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetTerminationPointGroupingRelationshipsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetTerminationPointGroupingRelationshipsException getTerminationPointGroupingRelationshipsException;

    public GetTerminationPointGroupingRelationshipsException() {
        super();
    }
    
    public GetTerminationPointGroupingRelationshipsException(String message) {
        super(message);
    }
    
    public GetTerminationPointGroupingRelationshipsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminationPointGroupingRelationshipsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetTerminationPointGroupingRelationshipsException getTerminationPointGroupingRelationshipsException) {
        super(message);
        this.getTerminationPointGroupingRelationshipsException = getTerminationPointGroupingRelationshipsException;
    }

    public GetTerminationPointGroupingRelationshipsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetTerminationPointGroupingRelationshipsException getTerminationPointGroupingRelationshipsException, Throwable cause) {
        super(message, cause);
        this.getTerminationPointGroupingRelationshipsException = getTerminationPointGroupingRelationshipsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetTerminationPointGroupingRelationshipsException getFaultInfo() {
        return this.getTerminationPointGroupingRelationshipsException;
    }
}
