
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.750+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTerminationPointPoolsIteratorException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetTerminationPointPoolsIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTerminationPointPoolsIteratorException;

    public GetTerminationPointPoolsIteratorException() {
        super();
    }
    
    public GetTerminationPointPoolsIteratorException(String message) {
        super(message);
    }
    
    public GetTerminationPointPoolsIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminationPointPoolsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTerminationPointPoolsIteratorException) {
        super(message);
        this.getTerminationPointPoolsIteratorException = getTerminationPointPoolsIteratorException;
    }

    public GetTerminationPointPoolsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTerminationPointPoolsIteratorException, Throwable cause) {
        super(message, cause);
        this.getTerminationPointPoolsIteratorException = getTerminationPointPoolsIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getTerminationPointPoolsIteratorException;
    }
}
