
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.562+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTerminationPointsIteratorException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetTerminationPointsIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTerminationPointsIteratorException;

    public GetTerminationPointsIteratorException() {
        super();
    }
    
    public GetTerminationPointsIteratorException(String message) {
        super(message);
    }
    
    public GetTerminationPointsIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminationPointsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTerminationPointsIteratorException) {
        super(message);
        this.getTerminationPointsIteratorException = getTerminationPointsIteratorException;
    }

    public GetTerminationPointsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTerminationPointsIteratorException, Throwable cause) {
        super(message, cause);
        this.getTerminationPointsIteratorException = getTerminationPointsIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getTerminationPointsIteratorException;
    }
}
