
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.515+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTrafficConditioningProfileAssociatedTpsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
public class GetTrafficConditioningProfileAssociatedTpsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tpr.v1.GetTrafficConditioningProfileAssociatedTpsException getTrafficConditioningProfileAssociatedTpsException;

    public GetTrafficConditioningProfileAssociatedTpsException() {
        super();
    }
    
    public GetTrafficConditioningProfileAssociatedTpsException(String message) {
        super(message);
    }
    
    public GetTrafficConditioningProfileAssociatedTpsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTrafficConditioningProfileAssociatedTpsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetTrafficConditioningProfileAssociatedTpsException getTrafficConditioningProfileAssociatedTpsException) {
        super(message);
        this.getTrafficConditioningProfileAssociatedTpsException = getTrafficConditioningProfileAssociatedTpsException;
    }

    public GetTrafficConditioningProfileAssociatedTpsException(String message, org.tmforum.mtop.mri.xsd.tpr.v1.GetTrafficConditioningProfileAssociatedTpsException getTrafficConditioningProfileAssociatedTpsException, Throwable cause) {
        super(message, cause);
        this.getTrafficConditioningProfileAssociatedTpsException = getTrafficConditioningProfileAssociatedTpsException;
    }

    public org.tmforum.mtop.mri.xsd.tpr.v1.GetTrafficConditioningProfileAssociatedTpsException getFaultInfo() {
        return this.getTrafficConditioningProfileAssociatedTpsException;
    }
}
