package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:30.968+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.tmforum.org/mtop/mri/wsdl/tpr/v1-0", name = "TerminationPointRetrieval_RPC")
@XmlSeeAlso({org.tmforum.mtop.nrf.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.hdr.v1.ObjectFactory.class, org.tmforum.mtop.vs.xsd.rr.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.gtp.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.tp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lay.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.tnp.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.ctp.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.coi.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.msg.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.gen.v1.ObjectFactory.class, org.tmforum.mtop.mri.xsd.tpr.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.ftp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.cri.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.tpdata.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.ptp.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.nam.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.fd.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pgp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lp.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.tppool.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TerminationPointRetrievalRPC {

    @WebResult(name = "getMemberTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getMemberTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.GetMemberTerminationPointsResponse getMemberTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getMemberTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetMemberTerminationPointsRequest mtopBody
    ) throws GetMemberTerminationPointsException;

    @WebResult(name = "getContainedPotentialConnectionTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getContainedPotentialConnectionTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getContainedPotentialConnectionTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getContainedPotentialConnectionTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionTerminationPointsType mtopBody
    ) throws GetContainedPotentialConnectionTerminationPointsException;

    @WebResult(name = "getAssociatedGroupTerminationPointResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAssociatedGroupTerminationPoint")
    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedGroupTerminationPointResponse getAssociatedGroupTerminationPoint(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAssociatedGroupTerminationPointRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedGroupTerminationPointRequest mtopBody
    ) throws GetAssociatedGroupTerminationPointException;

    @WebResult(name = "getGroupTerminationPointResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getGroupTerminationPoint")
    public org.tmforum.mtop.mri.xsd.tpr.v1.SingleGroupTerminationPointObjectResponseType getGroupTerminationPoint(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getGroupTerminationPointRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetGroupTerminationPointRequest mtopBody
    ) throws GetGroupTerminationPointException;

    @WebResult(name = "getTerminationPointPoolResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getTerminationPointPool")
    public org.tmforum.mtop.mri.xsd.tpr.v1.SingleTerminationPointPoolObjectResponseType getTerminationPointPool(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTerminationPointPoolRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetTerminationPointPoolRequest mtopBody
    ) throws GetTerminationPointPoolException;

    @WebResult(name = "getContainingTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getContainingTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getContainingTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getContainingTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile4Type mtopBody
    ) throws GetContainingTerminationPointsException;

    @WebResult(name = "getAssociatedTerminationPointResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAssociatedTerminationPoint")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAssociatedTerminationPoint(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAssociatedTerminationPointRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile2Type mtopBody
    ) throws GetAssociatedTerminationPointException;

    @WebResult(name = "getTrafficConditioningProfileAssociatedTpsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getTrafficConditioningProfileAssociatedTps")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getTrafficConditioningProfileAssociatedTps(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTrafficConditioningProfileAssociatedTpsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetTrafficConditioningProfileAssociatedTpsRequest mtopBody
    ) throws GetTrafficConditioningProfileAssociatedTpsException;

    @WebResult(name = "getContainingGroupTerminationPointResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getContainingGroupTerminationPoint")
    public org.tmforum.mtop.mri.xsd.tpr.v1.SingleGroupTerminationPointObjectResponseType getContainingGroupTerminationPoint(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getContainingGroupTerminationPointRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile4Type mtopBody
    ) throws GetContainingGroupTerminationPointException;

    @WebResult(name = "getTerminationPointsIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getTerminationPointsIterator")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getTerminationPointsIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTerminationPointsIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetTerminationPointsIteratorException;

    @WebResult(name = "getAllGroupTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllGroupTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleGroupTerminationPointObjectsResponseType getAllGroupTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllGroupTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllGroupTerminationPointsType mtopBody
    ) throws GetAllGroupTerminationPointsException;

    @WebResult(name = "getAllConnectionlessPortTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllConnectionlessPortTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionlessPortTerminationPointsResponse getAllConnectionlessPortTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllConnectionlessPortTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionlessPortTerminationPointsRequest mtopBody
    ) throws GetAllConnectionlessPortTerminationPointsException;

    @WebResult(name = "getContainedCurrentConnectionTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getContainedCurrentConnectionTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getContainedCurrentConnectionTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getContainedCurrentConnectionTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionTerminationPointsType mtopBody
    ) throws GetContainedCurrentConnectionTerminationPointsException;

    @WebResult(name = "getContainedInUseConnectionTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getContainedInUseConnectionTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getContainedInUseConnectionTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getContainedInUseConnectionTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionTerminationPointsType mtopBody
    ) throws GetContainedInUseConnectionTerminationPointsException;

    @WebResult(name = "getAllAssignedConnectionlessPortTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllAssignedConnectionlessPortTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignedConnectionlessPortTerminationPointsResponse getAllAssignedConnectionlessPortTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllAssignedConnectionlessPortTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignedConnectionlessPortTerminationPointsRequest mtopBody
    ) throws GetAllAssignedConnectionlessPortTerminationPointsException;

    @WebResult(name = "getAllTerminationPointPoolsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllTerminationPointPools")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointPoolObjectsResponseType getAllTerminationPointPools(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllTerminationPointPoolsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile1Type mtopBody
    ) throws GetAllTerminationPointPoolsException;

    @WebResult(name = "getAssociatedTerminationPointsWrtTmdResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAssociatedTerminationPointsWrtTmd")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAssociatedTerminationPointsWrtTmd(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAssociatedTerminationPointsWrtTmdRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedTerminationPointsWrtTmdRequest mtopBody
    ) throws GetAssociatedTerminationPointsWrtTmdException;

    @WebResult(name = "getTerminationPointPoolsIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getTerminationPointPoolsIterator")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointPoolObjectsResponseType getTerminationPointPoolsIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTerminationPointPoolsIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetTerminationPointPoolsIteratorException;

    @WebResult(name = "getAllSupportedPhysicalTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllSupportedPhysicalTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAllSupportedPhysicalTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllSupportedPhysicalTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile3Type mtopBody
    ) throws GetAllSupportedPhysicalTerminationPointsException;

    @WebResult(name = "getGroupTerminationPointsIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getGroupTerminationPointsIterator")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleGroupTerminationPointObjectsResponseType getGroupTerminationPointsIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getGroupTerminationPointsIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetGroupTerminationPointsIteratorException;

    @WebResult(name = "getTerminationPointResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getTerminationPoint")
    public org.tmforum.mtop.mri.xsd.tpr.v1.SingleTerminationPointObjectResponseType getTerminationPoint(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTerminationPointRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile2Type mtopBody
    ) throws GetTerminationPointException;

    @WebResult(name = "getAllPhysicalTerminationPointNamesResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllPhysicalTerminationPointNames")
    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointNamesResponse getAllPhysicalTerminationPointNames(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllPhysicalTerminationPointNamesRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointNamesRequest mtopBody
    ) throws GetAllPhysicalTerminationPointNamesException;

    @WebResult(name = "getAllPhysicalTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllPhysicalTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAllPhysicalTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllPhysicalTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointsType mtopBody
    ) throws GetAllPhysicalTerminationPointsException;

    @WebResult(name = "getAllPhysicalTerminationPointsWithoutFtpsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllPhysicalTerminationPointsWithoutFtps")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAllPhysicalTerminationPointsWithoutFtps(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllPhysicalTerminationPointsWithoutFtpsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointsType mtopBody
    ) throws GetAllPhysicalTerminationPointsWithoutFtpsException;

    @WebResult(name = "getAllAssignableConnectionlessPortTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllAssignableConnectionlessPortTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignableConnectionlessPortTerminationPointsResponse getAllAssignableConnectionlessPortTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllAssignableConnectionlessPortTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignableConnectionlessPortTerminationPointsRequest mtopBody
    ) throws GetAllAssignableConnectionlessPortTerminationPointsException;

    @WebResult(name = "getAllEdgePointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllEdgePoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAllEdgePoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllEdgePointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllEdgePointsType mtopBody
    ) throws GetAllEdgePointsException;

    @WebResult(name = "getTerminationPointGroupingRelationshipsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getTerminationPointGroupingRelationships")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleObjectNamesResponseType getTerminationPointGroupingRelationships(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTerminationPointGroupingRelationshipsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile2Type mtopBody
    ) throws GetTerminationPointGroupingRelationshipsException;

    @WebResult(name = "getAllFloatingTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllFloatingTerminationPoints")
    public org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType getAllFloatingTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllFloatingTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tpr/v1")
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointsType mtopBody
    ) throws GetAllFloatingTerminationPointsException;
}
