
package org.tmforum.mtop.mri.wsdl.tpr.v1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-19T08:33:29.375+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class TerminationPointRetrievalRPC_TerminationPointRetrievalRPC_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmforum.org/mtop/mri/wsdl/tpr/v1-0", "TerminationPointRetrievalHttp");

    private TerminationPointRetrievalRPC_TerminationPointRetrievalRPC_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TerminationPointRetrievalHttp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TerminationPointRetrievalHttp ss = new TerminationPointRetrievalHttp(wsdlURL, SERVICE_NAME);
        TerminationPointRetrievalRPC port = ss.getTerminationPointRetrievalRPC();  
        
        {
        System.out.println("Invoking getMemberTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getMemberTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getMemberTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getMemberTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetMemberTerminationPointsRequest _getMemberTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.GetMemberTerminationPointsResponse _getMemberTerminationPoints__return = port.getMemberTerminationPoints(_getMemberTerminationPoints_mtopHeader, _getMemberTerminationPoints_mtopBody);
            System.out.println("getMemberTerminationPoints.result=" + _getMemberTerminationPoints__return);

            System.out.println("getMemberTerminationPoints._getMemberTerminationPoints_mtopHeader=" + _getMemberTerminationPoints_mtopHeader.value);
        } catch (GetMemberTerminationPointsException e) { 
            System.out.println("Expected exception: GetMemberTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getContainedPotentialConnectionTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getContainedPotentialConnectionTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getContainedPotentialConnectionTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getContainedPotentialConnectionTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionTerminationPointsType _getContainedPotentialConnectionTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getContainedPotentialConnectionTerminationPoints__return = port.getContainedPotentialConnectionTerminationPoints(_getContainedPotentialConnectionTerminationPoints_mtopHeader, _getContainedPotentialConnectionTerminationPoints_mtopBody);
            System.out.println("getContainedPotentialConnectionTerminationPoints.result=" + _getContainedPotentialConnectionTerminationPoints__return);

            System.out.println("getContainedPotentialConnectionTerminationPoints._getContainedPotentialConnectionTerminationPoints_mtopHeader=" + _getContainedPotentialConnectionTerminationPoints_mtopHeader.value);
        } catch (GetContainedPotentialConnectionTerminationPointsException e) { 
            System.out.println("Expected exception: GetContainedPotentialConnectionTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAssociatedGroupTerminationPoint...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAssociatedGroupTerminationPoint_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAssociatedGroupTerminationPoint_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAssociatedGroupTerminationPoint_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedGroupTerminationPointRequest _getAssociatedGroupTerminationPoint_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedGroupTerminationPointResponse _getAssociatedGroupTerminationPoint__return = port.getAssociatedGroupTerminationPoint(_getAssociatedGroupTerminationPoint_mtopHeader, _getAssociatedGroupTerminationPoint_mtopBody);
            System.out.println("getAssociatedGroupTerminationPoint.result=" + _getAssociatedGroupTerminationPoint__return);

            System.out.println("getAssociatedGroupTerminationPoint._getAssociatedGroupTerminationPoint_mtopHeader=" + _getAssociatedGroupTerminationPoint_mtopHeader.value);
        } catch (GetAssociatedGroupTerminationPointException e) { 
            System.out.println("Expected exception: GetAssociatedGroupTerminationPointException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getGroupTerminationPoint...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getGroupTerminationPoint_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getGroupTerminationPoint_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getGroupTerminationPoint_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetGroupTerminationPointRequest _getGroupTerminationPoint_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.SingleGroupTerminationPointObjectResponseType _getGroupTerminationPoint__return = port.getGroupTerminationPoint(_getGroupTerminationPoint_mtopHeader, _getGroupTerminationPoint_mtopBody);
            System.out.println("getGroupTerminationPoint.result=" + _getGroupTerminationPoint__return);

            System.out.println("getGroupTerminationPoint._getGroupTerminationPoint_mtopHeader=" + _getGroupTerminationPoint_mtopHeader.value);
        } catch (GetGroupTerminationPointException e) { 
            System.out.println("Expected exception: GetGroupTerminationPointException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTerminationPointPool...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getTerminationPointPool_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getTerminationPointPool_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getTerminationPointPool_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetTerminationPointPoolRequest _getTerminationPointPool_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.SingleTerminationPointPoolObjectResponseType _getTerminationPointPool__return = port.getTerminationPointPool(_getTerminationPointPool_mtopHeader, _getTerminationPointPool_mtopBody);
            System.out.println("getTerminationPointPool.result=" + _getTerminationPointPool__return);

            System.out.println("getTerminationPointPool._getTerminationPointPool_mtopHeader=" + _getTerminationPointPool_mtopHeader.value);
        } catch (GetTerminationPointPoolException e) { 
            System.out.println("Expected exception: GetTerminationPointPoolException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getContainingTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getContainingTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getContainingTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getContainingTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile4Type _getContainingTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getContainingTerminationPoints__return = port.getContainingTerminationPoints(_getContainingTerminationPoints_mtopHeader, _getContainingTerminationPoints_mtopBody);
            System.out.println("getContainingTerminationPoints.result=" + _getContainingTerminationPoints__return);

            System.out.println("getContainingTerminationPoints._getContainingTerminationPoints_mtopHeader=" + _getContainingTerminationPoints_mtopHeader.value);
        } catch (GetContainingTerminationPointsException e) { 
            System.out.println("Expected exception: GetContainingTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAssociatedTerminationPoint...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAssociatedTerminationPoint_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAssociatedTerminationPoint_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAssociatedTerminationPoint_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile2Type _getAssociatedTerminationPoint_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAssociatedTerminationPoint__return = port.getAssociatedTerminationPoint(_getAssociatedTerminationPoint_mtopHeader, _getAssociatedTerminationPoint_mtopBody);
            System.out.println("getAssociatedTerminationPoint.result=" + _getAssociatedTerminationPoint__return);

            System.out.println("getAssociatedTerminationPoint._getAssociatedTerminationPoint_mtopHeader=" + _getAssociatedTerminationPoint_mtopHeader.value);
        } catch (GetAssociatedTerminationPointException e) { 
            System.out.println("Expected exception: GetAssociatedTerminationPointException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTrafficConditioningProfileAssociatedTps...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getTrafficConditioningProfileAssociatedTps_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getTrafficConditioningProfileAssociatedTps_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getTrafficConditioningProfileAssociatedTps_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetTrafficConditioningProfileAssociatedTpsRequest _getTrafficConditioningProfileAssociatedTps_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getTrafficConditioningProfileAssociatedTps__return = port.getTrafficConditioningProfileAssociatedTps(_getTrafficConditioningProfileAssociatedTps_mtopHeader, _getTrafficConditioningProfileAssociatedTps_mtopBody);
            System.out.println("getTrafficConditioningProfileAssociatedTps.result=" + _getTrafficConditioningProfileAssociatedTps__return);

            System.out.println("getTrafficConditioningProfileAssociatedTps._getTrafficConditioningProfileAssociatedTps_mtopHeader=" + _getTrafficConditioningProfileAssociatedTps_mtopHeader.value);
        } catch (GetTrafficConditioningProfileAssociatedTpsException e) { 
            System.out.println("Expected exception: GetTrafficConditioningProfileAssociatedTpsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getContainingGroupTerminationPoint...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getContainingGroupTerminationPoint_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getContainingGroupTerminationPoint_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getContainingGroupTerminationPoint_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile4Type _getContainingGroupTerminationPoint_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.SingleGroupTerminationPointObjectResponseType _getContainingGroupTerminationPoint__return = port.getContainingGroupTerminationPoint(_getContainingGroupTerminationPoint_mtopHeader, _getContainingGroupTerminationPoint_mtopBody);
            System.out.println("getContainingGroupTerminationPoint.result=" + _getContainingGroupTerminationPoint__return);

            System.out.println("getContainingGroupTerminationPoint._getContainingGroupTerminationPoint_mtopHeader=" + _getContainingGroupTerminationPoint_mtopHeader.value);
        } catch (GetContainingGroupTerminationPointException e) { 
            System.out.println("Expected exception: GetContainingGroupTerminationPointException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTerminationPointsIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getTerminationPointsIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getTerminationPointsIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getTerminationPointsIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getTerminationPointsIterator_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getTerminationPointsIterator__return = port.getTerminationPointsIterator(_getTerminationPointsIterator_mtopHeader, _getTerminationPointsIterator_mtopBody);
            System.out.println("getTerminationPointsIterator.result=" + _getTerminationPointsIterator__return);

            System.out.println("getTerminationPointsIterator._getTerminationPointsIterator_mtopHeader=" + _getTerminationPointsIterator_mtopHeader.value);
        } catch (GetTerminationPointsIteratorException e) { 
            System.out.println("Expected exception: GetTerminationPointsIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllGroupTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllGroupTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllGroupTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllGroupTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllGroupTerminationPointsType _getAllGroupTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleGroupTerminationPointObjectsResponseType _getAllGroupTerminationPoints__return = port.getAllGroupTerminationPoints(_getAllGroupTerminationPoints_mtopHeader, _getAllGroupTerminationPoints_mtopBody);
            System.out.println("getAllGroupTerminationPoints.result=" + _getAllGroupTerminationPoints__return);

            System.out.println("getAllGroupTerminationPoints._getAllGroupTerminationPoints_mtopHeader=" + _getAllGroupTerminationPoints_mtopHeader.value);
        } catch (GetAllGroupTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllGroupTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllConnectionlessPortTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllConnectionlessPortTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllConnectionlessPortTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllConnectionlessPortTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionlessPortTerminationPointsRequest _getAllConnectionlessPortTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionlessPortTerminationPointsResponse _getAllConnectionlessPortTerminationPoints__return = port.getAllConnectionlessPortTerminationPoints(_getAllConnectionlessPortTerminationPoints_mtopHeader, _getAllConnectionlessPortTerminationPoints_mtopBody);
            System.out.println("getAllConnectionlessPortTerminationPoints.result=" + _getAllConnectionlessPortTerminationPoints__return);

            System.out.println("getAllConnectionlessPortTerminationPoints._getAllConnectionlessPortTerminationPoints_mtopHeader=" + _getAllConnectionlessPortTerminationPoints_mtopHeader.value);
        } catch (GetAllConnectionlessPortTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllConnectionlessPortTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getContainedCurrentConnectionTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getContainedCurrentConnectionTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getContainedCurrentConnectionTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getContainedCurrentConnectionTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionTerminationPointsType _getContainedCurrentConnectionTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getContainedCurrentConnectionTerminationPoints__return = port.getContainedCurrentConnectionTerminationPoints(_getContainedCurrentConnectionTerminationPoints_mtopHeader, _getContainedCurrentConnectionTerminationPoints_mtopBody);
            System.out.println("getContainedCurrentConnectionTerminationPoints.result=" + _getContainedCurrentConnectionTerminationPoints__return);

            System.out.println("getContainedCurrentConnectionTerminationPoints._getContainedCurrentConnectionTerminationPoints_mtopHeader=" + _getContainedCurrentConnectionTerminationPoints_mtopHeader.value);
        } catch (GetContainedCurrentConnectionTerminationPointsException e) { 
            System.out.println("Expected exception: GetContainedCurrentConnectionTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getContainedInUseConnectionTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getContainedInUseConnectionTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getContainedInUseConnectionTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getContainedInUseConnectionTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllConnectionTerminationPointsType _getContainedInUseConnectionTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getContainedInUseConnectionTerminationPoints__return = port.getContainedInUseConnectionTerminationPoints(_getContainedInUseConnectionTerminationPoints_mtopHeader, _getContainedInUseConnectionTerminationPoints_mtopBody);
            System.out.println("getContainedInUseConnectionTerminationPoints.result=" + _getContainedInUseConnectionTerminationPoints__return);

            System.out.println("getContainedInUseConnectionTerminationPoints._getContainedInUseConnectionTerminationPoints_mtopHeader=" + _getContainedInUseConnectionTerminationPoints_mtopHeader.value);
        } catch (GetContainedInUseConnectionTerminationPointsException e) { 
            System.out.println("Expected exception: GetContainedInUseConnectionTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllAssignedConnectionlessPortTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllAssignedConnectionlessPortTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllAssignedConnectionlessPortTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllAssignedConnectionlessPortTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignedConnectionlessPortTerminationPointsRequest _getAllAssignedConnectionlessPortTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignedConnectionlessPortTerminationPointsResponse _getAllAssignedConnectionlessPortTerminationPoints__return = port.getAllAssignedConnectionlessPortTerminationPoints(_getAllAssignedConnectionlessPortTerminationPoints_mtopHeader, _getAllAssignedConnectionlessPortTerminationPoints_mtopBody);
            System.out.println("getAllAssignedConnectionlessPortTerminationPoints.result=" + _getAllAssignedConnectionlessPortTerminationPoints__return);

            System.out.println("getAllAssignedConnectionlessPortTerminationPoints._getAllAssignedConnectionlessPortTerminationPoints_mtopHeader=" + _getAllAssignedConnectionlessPortTerminationPoints_mtopHeader.value);
        } catch (GetAllAssignedConnectionlessPortTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllAssignedConnectionlessPortTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllTerminationPointPools...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllTerminationPointPools_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllTerminationPointPools_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllTerminationPointPools_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile1Type _getAllTerminationPointPools_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointPoolObjectsResponseType _getAllTerminationPointPools__return = port.getAllTerminationPointPools(_getAllTerminationPointPools_mtopHeader, _getAllTerminationPointPools_mtopBody);
            System.out.println("getAllTerminationPointPools.result=" + _getAllTerminationPointPools__return);

            System.out.println("getAllTerminationPointPools._getAllTerminationPointPools_mtopHeader=" + _getAllTerminationPointPools_mtopHeader.value);
        } catch (GetAllTerminationPointPoolsException e) { 
            System.out.println("Expected exception: GetAllTerminationPointPoolsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAssociatedTerminationPointsWrtTmd...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAssociatedTerminationPointsWrtTmd_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAssociatedTerminationPointsWrtTmd_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAssociatedTerminationPointsWrtTmd_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAssociatedTerminationPointsWrtTmdRequest _getAssociatedTerminationPointsWrtTmd_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAssociatedTerminationPointsWrtTmd__return = port.getAssociatedTerminationPointsWrtTmd(_getAssociatedTerminationPointsWrtTmd_mtopHeader, _getAssociatedTerminationPointsWrtTmd_mtopBody);
            System.out.println("getAssociatedTerminationPointsWrtTmd.result=" + _getAssociatedTerminationPointsWrtTmd__return);

            System.out.println("getAssociatedTerminationPointsWrtTmd._getAssociatedTerminationPointsWrtTmd_mtopHeader=" + _getAssociatedTerminationPointsWrtTmd_mtopHeader.value);
        } catch (GetAssociatedTerminationPointsWrtTmdException e) { 
            System.out.println("Expected exception: GetAssociatedTerminationPointsWrtTmdException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTerminationPointPoolsIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getTerminationPointPoolsIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getTerminationPointPoolsIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getTerminationPointPoolsIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getTerminationPointPoolsIterator_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointPoolObjectsResponseType _getTerminationPointPoolsIterator__return = port.getTerminationPointPoolsIterator(_getTerminationPointPoolsIterator_mtopHeader, _getTerminationPointPoolsIterator_mtopBody);
            System.out.println("getTerminationPointPoolsIterator.result=" + _getTerminationPointPoolsIterator__return);

            System.out.println("getTerminationPointPoolsIterator._getTerminationPointPoolsIterator_mtopHeader=" + _getTerminationPointPoolsIterator_mtopHeader.value);
        } catch (GetTerminationPointPoolsIteratorException e) { 
            System.out.println("Expected exception: GetTerminationPointPoolsIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllSupportedPhysicalTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllSupportedPhysicalTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllSupportedPhysicalTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllSupportedPhysicalTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile3Type _getAllSupportedPhysicalTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAllSupportedPhysicalTerminationPoints__return = port.getAllSupportedPhysicalTerminationPoints(_getAllSupportedPhysicalTerminationPoints_mtopHeader, _getAllSupportedPhysicalTerminationPoints_mtopBody);
            System.out.println("getAllSupportedPhysicalTerminationPoints.result=" + _getAllSupportedPhysicalTerminationPoints__return);

            System.out.println("getAllSupportedPhysicalTerminationPoints._getAllSupportedPhysicalTerminationPoints_mtopHeader=" + _getAllSupportedPhysicalTerminationPoints_mtopHeader.value);
        } catch (GetAllSupportedPhysicalTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllSupportedPhysicalTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getGroupTerminationPointsIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getGroupTerminationPointsIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getGroupTerminationPointsIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getGroupTerminationPointsIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getGroupTerminationPointsIterator_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleGroupTerminationPointObjectsResponseType _getGroupTerminationPointsIterator__return = port.getGroupTerminationPointsIterator(_getGroupTerminationPointsIterator_mtopHeader, _getGroupTerminationPointsIterator_mtopBody);
            System.out.println("getGroupTerminationPointsIterator.result=" + _getGroupTerminationPointsIterator__return);

            System.out.println("getGroupTerminationPointsIterator._getGroupTerminationPointsIterator_mtopHeader=" + _getGroupTerminationPointsIterator_mtopHeader.value);
        } catch (GetGroupTerminationPointsIteratorException e) { 
            System.out.println("Expected exception: GetGroupTerminationPointsIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTerminationPoint...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getTerminationPoint_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getTerminationPoint_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getTerminationPoint_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile2Type _getTerminationPoint_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.SingleTerminationPointObjectResponseType _getTerminationPoint__return = port.getTerminationPoint(_getTerminationPoint_mtopHeader, _getTerminationPoint_mtopBody);
            System.out.println("getTerminationPoint.result=" + _getTerminationPoint__return);

            System.out.println("getTerminationPoint._getTerminationPoint_mtopHeader=" + _getTerminationPoint_mtopHeader.value);
        } catch (GetTerminationPointException e) { 
            System.out.println("Expected exception: GetTerminationPointException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllPhysicalTerminationPointNames...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllPhysicalTerminationPointNames_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllPhysicalTerminationPointNames_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllPhysicalTerminationPointNames_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointNamesRequest _getAllPhysicalTerminationPointNames_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.GetAllPhysicalTerminationPointNamesResponse _getAllPhysicalTerminationPointNames__return = port.getAllPhysicalTerminationPointNames(_getAllPhysicalTerminationPointNames_mtopHeader, _getAllPhysicalTerminationPointNames_mtopBody);
            System.out.println("getAllPhysicalTerminationPointNames.result=" + _getAllPhysicalTerminationPointNames__return);

            System.out.println("getAllPhysicalTerminationPointNames._getAllPhysicalTerminationPointNames_mtopHeader=" + _getAllPhysicalTerminationPointNames_mtopHeader.value);
        } catch (GetAllPhysicalTerminationPointNamesException e) { 
            System.out.println("Expected exception: GetAllPhysicalTerminationPointNamesException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllPhysicalTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllPhysicalTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllPhysicalTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllPhysicalTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointsType _getAllPhysicalTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAllPhysicalTerminationPoints__return = port.getAllPhysicalTerminationPoints(_getAllPhysicalTerminationPoints_mtopHeader, _getAllPhysicalTerminationPoints_mtopBody);
            System.out.println("getAllPhysicalTerminationPoints.result=" + _getAllPhysicalTerminationPoints__return);

            System.out.println("getAllPhysicalTerminationPoints._getAllPhysicalTerminationPoints_mtopHeader=" + _getAllPhysicalTerminationPoints_mtopHeader.value);
        } catch (GetAllPhysicalTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllPhysicalTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllPhysicalTerminationPointsWithoutFtps...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllPhysicalTerminationPointsWithoutFtps_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllPhysicalTerminationPointsWithoutFtps_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllPhysicalTerminationPointsWithoutFtps_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointsType _getAllPhysicalTerminationPointsWithoutFtps_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAllPhysicalTerminationPointsWithoutFtps__return = port.getAllPhysicalTerminationPointsWithoutFtps(_getAllPhysicalTerminationPointsWithoutFtps_mtopHeader, _getAllPhysicalTerminationPointsWithoutFtps_mtopBody);
            System.out.println("getAllPhysicalTerminationPointsWithoutFtps.result=" + _getAllPhysicalTerminationPointsWithoutFtps__return);

            System.out.println("getAllPhysicalTerminationPointsWithoutFtps._getAllPhysicalTerminationPointsWithoutFtps_mtopHeader=" + _getAllPhysicalTerminationPointsWithoutFtps_mtopHeader.value);
        } catch (GetAllPhysicalTerminationPointsWithoutFtpsException e) { 
            System.out.println("Expected exception: GetAllPhysicalTerminationPointsWithoutFtpsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllAssignableConnectionlessPortTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllAssignableConnectionlessPortTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllAssignableConnectionlessPortTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllAssignableConnectionlessPortTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignableConnectionlessPortTerminationPointsRequest _getAllAssignableConnectionlessPortTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.GetAllAssignableConnectionlessPortTerminationPointsResponse _getAllAssignableConnectionlessPortTerminationPoints__return = port.getAllAssignableConnectionlessPortTerminationPoints(_getAllAssignableConnectionlessPortTerminationPoints_mtopHeader, _getAllAssignableConnectionlessPortTerminationPoints_mtopBody);
            System.out.println("getAllAssignableConnectionlessPortTerminationPoints.result=" + _getAllAssignableConnectionlessPortTerminationPoints__return);

            System.out.println("getAllAssignableConnectionlessPortTerminationPoints._getAllAssignableConnectionlessPortTerminationPoints_mtopHeader=" + _getAllAssignableConnectionlessPortTerminationPoints_mtopHeader.value);
        } catch (GetAllAssignableConnectionlessPortTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllAssignableConnectionlessPortTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllEdgePoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllEdgePoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllEdgePoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllEdgePoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllEdgePointsType _getAllEdgePoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAllEdgePoints__return = port.getAllEdgePoints(_getAllEdgePoints_mtopHeader, _getAllEdgePoints_mtopBody);
            System.out.println("getAllEdgePoints.result=" + _getAllEdgePoints__return);

            System.out.println("getAllEdgePoints._getAllEdgePoints_mtopHeader=" + _getAllEdgePoints_mtopHeader.value);
        } catch (GetAllEdgePointsException e) { 
            System.out.println("Expected exception: GetAllEdgePointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTerminationPointGroupingRelationships...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getTerminationPointGroupingRelationships_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getTerminationPointGroupingRelationships_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getTerminationPointGroupingRelationships_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.RequestProfile2Type _getTerminationPointGroupingRelationships_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleObjectNamesResponseType _getTerminationPointGroupingRelationships__return = port.getTerminationPointGroupingRelationships(_getTerminationPointGroupingRelationships_mtopHeader, _getTerminationPointGroupingRelationships_mtopBody);
            System.out.println("getTerminationPointGroupingRelationships.result=" + _getTerminationPointGroupingRelationships__return);

            System.out.println("getTerminationPointGroupingRelationships._getTerminationPointGroupingRelationships_mtopHeader=" + _getTerminationPointGroupingRelationships_mtopHeader.value);
        } catch (GetTerminationPointGroupingRelationshipsException e) { 
            System.out.println("Expected exception: GetTerminationPointGroupingRelationshipsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllFloatingTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllFloatingTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllFloatingTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllFloatingTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.mri.xsd.tpr.v1.GetAllTerminationPointsType _getAllFloatingTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.mri.xsd.tpr.v1.MultipleTerminationPointObjectsResponseType _getAllFloatingTerminationPoints__return = port.getAllFloatingTerminationPoints(_getAllFloatingTerminationPoints_mtopHeader, _getAllFloatingTerminationPoints_mtopBody);
            System.out.println("getAllFloatingTerminationPoints.result=" + _getAllFloatingTerminationPoints__return);

            System.out.println("getAllFloatingTerminationPoints._getAllFloatingTerminationPoints_mtopHeader=" + _getAllFloatingTerminationPoints_mtopHeader.value);
        } catch (GetAllFloatingTerminationPointsException e) { 
            System.out.println("Expected exception: GetAllFloatingTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
