
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.500+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllCurrentPerformanceMonitoringDataException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetAllCurrentPerformanceMonitoringDataException extends Exception {
    
    private org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllCurrentPerformanceMonitoringDataException getAllCurrentPerformanceMonitoringDataException;

    public GetAllCurrentPerformanceMonitoringDataException() {
        super();
    }
    
    public GetAllCurrentPerformanceMonitoringDataException(String message) {
        super(message);
    }
    
    public GetAllCurrentPerformanceMonitoringDataException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllCurrentPerformanceMonitoringDataException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllCurrentPerformanceMonitoringDataException getAllCurrentPerformanceMonitoringDataException) {
        super(message);
        this.getAllCurrentPerformanceMonitoringDataException = getAllCurrentPerformanceMonitoringDataException;
    }

    public GetAllCurrentPerformanceMonitoringDataException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllCurrentPerformanceMonitoringDataException getAllCurrentPerformanceMonitoringDataException, Throwable cause) {
        super(message, cause);
        this.getAllCurrentPerformanceMonitoringDataException = getAllCurrentPerformanceMonitoringDataException;
    }

    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllCurrentPerformanceMonitoringDataException getFaultInfo() {
        return this.getAllCurrentPerformanceMonitoringDataException;
    }
}
