
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.312+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllPerformanceMonitoringPointsException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetAllPerformanceMonitoringPointsException extends Exception {
    
    private org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointsException getAllPerformanceMonitoringPointsException;

    public GetAllPerformanceMonitoringPointsException() {
        super();
    }
    
    public GetAllPerformanceMonitoringPointsException(String message) {
        super(message);
    }
    
    public GetAllPerformanceMonitoringPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllPerformanceMonitoringPointsException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointsException getAllPerformanceMonitoringPointsException) {
        super(message);
        this.getAllPerformanceMonitoringPointsException = getAllPerformanceMonitoringPointsException;
    }

    public GetAllPerformanceMonitoringPointsException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointsException getAllPerformanceMonitoringPointsException, Throwable cause) {
        super(message, cause);
        this.getAllPerformanceMonitoringPointsException = getAllPerformanceMonitoringPointsException;
    }

    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointsException getFaultInfo() {
        return this.getAllPerformanceMonitoringPointsException;
    }
}
