
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.390+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllPerformanceMonitoringPointNamesException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetAllPerformanceMonitoringPointNamesException extends Exception {
    
    private org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointNamesException getAllPerformanceMonitoringPointNamesException;

    public GetAllPerformanceMonitoringPointNamesException() {
        super();
    }
    
    public GetAllPerformanceMonitoringPointNamesException(String message) {
        super(message);
    }
    
    public GetAllPerformanceMonitoringPointNamesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllPerformanceMonitoringPointNamesException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointNamesException getAllPerformanceMonitoringPointNamesException) {
        super(message);
        this.getAllPerformanceMonitoringPointNamesException = getAllPerformanceMonitoringPointNamesException;
    }

    public GetAllPerformanceMonitoringPointNamesException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointNamesException getAllPerformanceMonitoringPointNamesException, Throwable cause) {
        super(message, cause);
        this.getAllPerformanceMonitoringPointNamesException = getAllPerformanceMonitoringPointNamesException;
    }

    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointNamesException getFaultInfo() {
        return this.getAllPerformanceMonitoringPointNamesException;
    }
}
