
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.468+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getHoldingTimeException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetHoldingTimeException extends Exception {
    
    private org.tmforum.mtop.rpm.xsd.pmr.v1.GetHoldingTimeException getHoldingTimeException;

    public GetHoldingTimeException() {
        super();
    }
    
    public GetHoldingTimeException(String message) {
        super(message);
    }
    
    public GetHoldingTimeException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetHoldingTimeException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetHoldingTimeException getHoldingTimeException) {
        super(message);
        this.getHoldingTimeException = getHoldingTimeException;
    }

    public GetHoldingTimeException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetHoldingTimeException getHoldingTimeException, Throwable cause) {
        super(message, cause);
        this.getHoldingTimeException = getHoldingTimeException;
    }

    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetHoldingTimeException getFaultInfo() {
        return this.getHoldingTimeException;
    }
}
