
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.406+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getPerformanceMonitoringPointsIteratorException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetPerformanceMonitoringPointsIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getPerformanceMonitoringPointsIteratorException;

    public GetPerformanceMonitoringPointsIteratorException() {
        super();
    }
    
    public GetPerformanceMonitoringPointsIteratorException(String message) {
        super(message);
    }
    
    public GetPerformanceMonitoringPointsIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetPerformanceMonitoringPointsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getPerformanceMonitoringPointsIteratorException) {
        super(message);
        this.getPerformanceMonitoringPointsIteratorException = getPerformanceMonitoringPointsIteratorException;
    }

    public GetPerformanceMonitoringPointsIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getPerformanceMonitoringPointsIteratorException, Throwable cause) {
        super(message, cause);
        this.getPerformanceMonitoringPointsIteratorException = getPerformanceMonitoringPointsIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getPerformanceMonitoringPointsIteratorException;
    }
}
