
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.359+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getProfileAssociatedTerminationPointsException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetProfileAssociatedTerminationPointsException extends Exception {
    
    private org.tmforum.mtop.rpm.xsd.pmr.v1.GetProfileAssociatedTerminationPointsException getProfileAssociatedTerminationPointsException;

    public GetProfileAssociatedTerminationPointsException() {
        super();
    }
    
    public GetProfileAssociatedTerminationPointsException(String message) {
        super(message);
    }
    
    public GetProfileAssociatedTerminationPointsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetProfileAssociatedTerminationPointsException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetProfileAssociatedTerminationPointsException getProfileAssociatedTerminationPointsException) {
        super(message);
        this.getProfileAssociatedTerminationPointsException = getProfileAssociatedTerminationPointsException;
    }

    public GetProfileAssociatedTerminationPointsException(String message, org.tmforum.mtop.rpm.xsd.pmr.v1.GetProfileAssociatedTerminationPointsException getProfileAssociatedTerminationPointsException, Throwable cause) {
        super(message, cause);
        this.getProfileAssociatedTerminationPointsException = getProfileAssociatedTerminationPointsException;
    }

    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetProfileAssociatedTerminationPointsException getFaultInfo() {
        return this.getProfileAssociatedTerminationPointsException;
    }
}
