
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.468+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getPerformanceMonitoringPointNamesIteratorException", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
public class GetPerformanceMonitoringPointNamesIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getPerformanceMonitoringPointNamesIteratorException;

    public GetPerformanceMonitoringPointNamesIteratorException() {
        super();
    }
    
    public GetPerformanceMonitoringPointNamesIteratorException(String message) {
        super(message);
    }
    
    public GetPerformanceMonitoringPointNamesIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetPerformanceMonitoringPointNamesIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getPerformanceMonitoringPointNamesIteratorException) {
        super(message);
        this.getPerformanceMonitoringPointNamesIteratorException = getPerformanceMonitoringPointNamesIteratorException;
    }

    public GetPerformanceMonitoringPointNamesIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getPerformanceMonitoringPointNamesIteratorException, Throwable cause) {
        super(message, cause);
        this.getPerformanceMonitoringPointNamesIteratorException = getPerformanceMonitoringPointNamesIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getPerformanceMonitoringPointNamesIteratorException;
    }
}
