package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.515+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "PerformanceManagementRetrievalHttp", 
                  wsdlLocation = "http://192.168.189.46:9997/PerformanceManagementRetrieval?wsdl",
                  targetNamespace = "http://www.tmforum.org/mtop/rpm/wsdl/pmr/v1-0") 
public class PerformanceManagementRetrievalHttp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmforum.org/mtop/rpm/wsdl/pmr/v1-0", "PerformanceManagementRetrievalHttp");
    public final static QName PerformanceManagementRetrieval = new QName("http://www.tmforum.org/mtop/rpm/wsdl/pmr/v1-0", "PerformanceManagementRetrieval");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.189.46:9997/PerformanceManagementRetrieval?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PerformanceManagementRetrievalHttp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.189.46:9997/PerformanceManagementRetrieval?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PerformanceManagementRetrievalHttp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PerformanceManagementRetrievalHttp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerformanceManagementRetrievalHttp() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PerformanceManagementRetrieval
     */
    @WebEndpoint(name = "PerformanceManagementRetrieval")
    public PerformanceManagementRetrieval getPerformanceManagementRetrieval() {
        return super.getPort(PerformanceManagementRetrieval, PerformanceManagementRetrieval.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerformanceManagementRetrieval
     */
    @WebEndpoint(name = "PerformanceManagementRetrieval")
    public PerformanceManagementRetrieval getPerformanceManagementRetrieval(WebServiceFeature... features) {
        return super.getPort(PerformanceManagementRetrieval, PerformanceManagementRetrieval.class, features);
    }

}
