package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.500+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.tmforum.org/mtop/rpm/wsdl/pmr/v1-0", name = "PerformanceManagementRetrieval")
@XmlSeeAlso({org.tmforum.mtop.fmw.xsd.hdr.v1.ObjectFactory.class, org.tmforum.mtop.vs.xsd.rr.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pmth.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pmp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lay.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.tnp.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pmtgt.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.coi.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pmmsrt.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.msg.v1.ObjectFactory.class, org.tmforum.mtop.rpm.xsd.pmr.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.gen.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.cri.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.itu.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pm.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.nam.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pgp.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pmpar.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pmdata.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PerformanceManagementRetrieval {

    @WebResult(name = "getAllPerformanceMonitoringPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllPerformanceMonitoringPoints")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectsResponseType getAllPerformanceMonitoringPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllPerformanceMonitoringPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointsRequest mtopBody
    ) throws GetAllPerformanceMonitoringPointsException;

    @WebResult(name = "getProfileAssociatedTerminationPointsResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getProfileAssociatedTerminationPoints")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultipleProfileAssociatedTerminationPointObjectNamesResponseType getProfileAssociatedTerminationPoints(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getProfileAssociatedTerminationPointsRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetProfileAssociatedTerminationPointsRequest mtopBody
    ) throws GetProfileAssociatedTerminationPointsException;

    @WebResult(name = "getPerformanceMonitoringDataIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getPerformanceMonitoringDataIterator")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringDataObjectsResponseType getPerformanceMonitoringDataIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getPerformanceMonitoringDataIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetPerformanceMonitoringDataIteratorException;

    @WebResult(name = "getAllPerformanceMonitoringPointNamesResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllPerformanceMonitoringPointNames")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectNamesResponseType getAllPerformanceMonitoringPointNames(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllPerformanceMonitoringPointNamesRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointNamesRequest mtopBody
    ) throws GetAllPerformanceMonitoringPointNamesException;

    @WebResult(name = "getPerformanceMonitoringPointsIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getPerformanceMonitoringPointsIterator")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectsResponseType getPerformanceMonitoringPointsIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getPerformanceMonitoringPointsIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetPerformanceMonitoringPointsIteratorException;

    @WebResult(name = "getPfmInstanceByResourceResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getPfmInstanceByResource")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetPfmInstanceByResourceResponse getPfmInstanceByResource(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getPfmInstanceByResourceRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetPfmInstanceByResourceRequest mtopBody
    ) throws GetPfmInstanceByResourceException;

    @WebResult(name = "getHoldingTimeResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getHoldingTime")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetHoldingTimeResponse getHoldingTime(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getHoldingTimeRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        java.lang.Object mtopBody
    ) throws GetHoldingTimeException;

    @WebResult(name = "getPerformanceMonitoringPointNamesIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getPerformanceMonitoringPointNamesIterator")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectNamesResponseType getPerformanceMonitoringPointNamesIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getPerformanceMonitoringPointNamesIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetPerformanceMonitoringPointNamesIteratorException;

    @WebResult(name = "getMePerformanceMonitoringCapabilitiesResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getMePerformanceMonitoringCapabilities")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.GetMePerformanceMonitoringCapabilitiesResponse getMePerformanceMonitoringCapabilities(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getMePerformanceMonitoringCapabilitiesRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetMePerformanceMonitoringCapabilitiesRequest mtopBody
    ) throws GetMePerformanceMonitoringCapabilitiesException;

    @WebResult(name = "getHistoryPerformanceMonitoringDataResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getHistoryPerformanceMonitoringData")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringDataObjectsResponseType getHistoryPerformanceMonitoringData(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getHistoryPerformanceMonitoringDataRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetHistoryPerformanceMonitoringDataRequest mtopBody
    ) throws GetHistoryPerformanceMonitoringDataException;

    @WebResult(name = "getAllCurrentPerformanceMonitoringDataResponse", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllCurrentPerformanceMonitoringData")
    public org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringDataObjectsResponseType getAllCurrentPerformanceMonitoringData(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllCurrentPerformanceMonitoringDataRequest", targetNamespace = "http://www.tmforum.org/mtop/rpm/xsd/pmr/v1")
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllCurrentPerformanceMonitoringDataRequest mtopBody
    ) throws GetAllCurrentPerformanceMonitoringDataException;
}
