
package org.tmforum.mtop.rpm.wsdl.pmr.v1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:37:25.093+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class PerformanceManagementRetrieval_PerformanceManagementRetrieval_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmforum.org/mtop/rpm/wsdl/pmr/v1-0", "PerformanceManagementRetrievalHttp");

    private PerformanceManagementRetrieval_PerformanceManagementRetrieval_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PerformanceManagementRetrievalHttp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PerformanceManagementRetrievalHttp ss = new PerformanceManagementRetrievalHttp(wsdlURL, SERVICE_NAME);
        PerformanceManagementRetrieval port = ss.getPerformanceManagementRetrieval();  
        
        {
        System.out.println("Invoking getAllPerformanceMonitoringPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllPerformanceMonitoringPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllPerformanceMonitoringPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllPerformanceMonitoringPoints_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointsRequest _getAllPerformanceMonitoringPoints_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectsResponseType _getAllPerformanceMonitoringPoints__return = port.getAllPerformanceMonitoringPoints(_getAllPerformanceMonitoringPoints_mtopHeader, _getAllPerformanceMonitoringPoints_mtopBody);
            System.out.println("getAllPerformanceMonitoringPoints.result=" + _getAllPerformanceMonitoringPoints__return);

            System.out.println("getAllPerformanceMonitoringPoints._getAllPerformanceMonitoringPoints_mtopHeader=" + _getAllPerformanceMonitoringPoints_mtopHeader.value);
        } catch (GetAllPerformanceMonitoringPointsException e) { 
            System.out.println("Expected exception: GetAllPerformanceMonitoringPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getProfileAssociatedTerminationPoints...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getProfileAssociatedTerminationPoints_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getProfileAssociatedTerminationPoints_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getProfileAssociatedTerminationPoints_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetProfileAssociatedTerminationPointsRequest _getProfileAssociatedTerminationPoints_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultipleProfileAssociatedTerminationPointObjectNamesResponseType _getProfileAssociatedTerminationPoints__return = port.getProfileAssociatedTerminationPoints(_getProfileAssociatedTerminationPoints_mtopHeader, _getProfileAssociatedTerminationPoints_mtopBody);
            System.out.println("getProfileAssociatedTerminationPoints.result=" + _getProfileAssociatedTerminationPoints__return);

            System.out.println("getProfileAssociatedTerminationPoints._getProfileAssociatedTerminationPoints_mtopHeader=" + _getProfileAssociatedTerminationPoints_mtopHeader.value);
        } catch (GetProfileAssociatedTerminationPointsException e) { 
            System.out.println("Expected exception: GetProfileAssociatedTerminationPointsException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPerformanceMonitoringDataIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getPerformanceMonitoringDataIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getPerformanceMonitoringDataIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getPerformanceMonitoringDataIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getPerformanceMonitoringDataIterator_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringDataObjectsResponseType _getPerformanceMonitoringDataIterator__return = port.getPerformanceMonitoringDataIterator(_getPerformanceMonitoringDataIterator_mtopHeader, _getPerformanceMonitoringDataIterator_mtopBody);
            System.out.println("getPerformanceMonitoringDataIterator.result=" + _getPerformanceMonitoringDataIterator__return);

            System.out.println("getPerformanceMonitoringDataIterator._getPerformanceMonitoringDataIterator_mtopHeader=" + _getPerformanceMonitoringDataIterator_mtopHeader.value);
        } catch (GetPerformanceMonitoringDataIteratorException e) { 
            System.out.println("Expected exception: GetPerformanceMonitoringDataIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllPerformanceMonitoringPointNames...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllPerformanceMonitoringPointNames_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllPerformanceMonitoringPointNames_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllPerformanceMonitoringPointNames_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllPerformanceMonitoringPointNamesRequest _getAllPerformanceMonitoringPointNames_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectNamesResponseType _getAllPerformanceMonitoringPointNames__return = port.getAllPerformanceMonitoringPointNames(_getAllPerformanceMonitoringPointNames_mtopHeader, _getAllPerformanceMonitoringPointNames_mtopBody);
            System.out.println("getAllPerformanceMonitoringPointNames.result=" + _getAllPerformanceMonitoringPointNames__return);

            System.out.println("getAllPerformanceMonitoringPointNames._getAllPerformanceMonitoringPointNames_mtopHeader=" + _getAllPerformanceMonitoringPointNames_mtopHeader.value);
        } catch (GetAllPerformanceMonitoringPointNamesException e) { 
            System.out.println("Expected exception: GetAllPerformanceMonitoringPointNamesException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPerformanceMonitoringPointsIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getPerformanceMonitoringPointsIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getPerformanceMonitoringPointsIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getPerformanceMonitoringPointsIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getPerformanceMonitoringPointsIterator_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectsResponseType _getPerformanceMonitoringPointsIterator__return = port.getPerformanceMonitoringPointsIterator(_getPerformanceMonitoringPointsIterator_mtopHeader, _getPerformanceMonitoringPointsIterator_mtopBody);
            System.out.println("getPerformanceMonitoringPointsIterator.result=" + _getPerformanceMonitoringPointsIterator__return);

            System.out.println("getPerformanceMonitoringPointsIterator._getPerformanceMonitoringPointsIterator_mtopHeader=" + _getPerformanceMonitoringPointsIterator_mtopHeader.value);
        } catch (GetPerformanceMonitoringPointsIteratorException e) { 
            System.out.println("Expected exception: GetPerformanceMonitoringPointsIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPfmInstanceByResource...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getPfmInstanceByResource_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getPfmInstanceByResource_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getPfmInstanceByResource_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetPfmInstanceByResourceRequest _getPfmInstanceByResource_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.GetPfmInstanceByResourceResponse _getPfmInstanceByResource__return = port.getPfmInstanceByResource(_getPfmInstanceByResource_mtopHeader, _getPfmInstanceByResource_mtopBody);
            System.out.println("getPfmInstanceByResource.result=" + _getPfmInstanceByResource__return);

            System.out.println("getPfmInstanceByResource._getPfmInstanceByResource_mtopHeader=" + _getPfmInstanceByResource_mtopHeader.value);
        } catch (GetPfmInstanceByResourceException e) { 
            System.out.println("Expected exception: GetPfmInstanceByResourceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getHoldingTime...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getHoldingTime_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getHoldingTime_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getHoldingTime_mtopHeaderVal);
        java.lang.Object _getHoldingTime_mtopBody = new java.lang.Object();
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.GetHoldingTimeResponse _getHoldingTime__return = port.getHoldingTime(_getHoldingTime_mtopHeader, _getHoldingTime_mtopBody);
            System.out.println("getHoldingTime.result=" + _getHoldingTime__return);

            System.out.println("getHoldingTime._getHoldingTime_mtopHeader=" + _getHoldingTime_mtopHeader.value);
        } catch (GetHoldingTimeException e) { 
            System.out.println("Expected exception: GetHoldingTimeException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPerformanceMonitoringPointNamesIterator...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getPerformanceMonitoringPointNamesIterator_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getPerformanceMonitoringPointNamesIterator_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getPerformanceMonitoringPointNamesIterator_mtopHeaderVal);
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType _getPerformanceMonitoringPointNamesIterator_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringPointObjectNamesResponseType _getPerformanceMonitoringPointNamesIterator__return = port.getPerformanceMonitoringPointNamesIterator(_getPerformanceMonitoringPointNamesIterator_mtopHeader, _getPerformanceMonitoringPointNamesIterator_mtopBody);
            System.out.println("getPerformanceMonitoringPointNamesIterator.result=" + _getPerformanceMonitoringPointNamesIterator__return);

            System.out.println("getPerformanceMonitoringPointNamesIterator._getPerformanceMonitoringPointNamesIterator_mtopHeader=" + _getPerformanceMonitoringPointNamesIterator_mtopHeader.value);
        } catch (GetPerformanceMonitoringPointNamesIteratorException e) { 
            System.out.println("Expected exception: GetPerformanceMonitoringPointNamesIteratorException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMePerformanceMonitoringCapabilities...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getMePerformanceMonitoringCapabilities_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getMePerformanceMonitoringCapabilities_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getMePerformanceMonitoringCapabilities_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetMePerformanceMonitoringCapabilitiesRequest _getMePerformanceMonitoringCapabilities_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.GetMePerformanceMonitoringCapabilitiesResponse _getMePerformanceMonitoringCapabilities__return = port.getMePerformanceMonitoringCapabilities(_getMePerformanceMonitoringCapabilities_mtopHeader, _getMePerformanceMonitoringCapabilities_mtopBody);
            System.out.println("getMePerformanceMonitoringCapabilities.result=" + _getMePerformanceMonitoringCapabilities__return);

            System.out.println("getMePerformanceMonitoringCapabilities._getMePerformanceMonitoringCapabilities_mtopHeader=" + _getMePerformanceMonitoringCapabilities_mtopHeader.value);
        } catch (GetMePerformanceMonitoringCapabilitiesException e) { 
            System.out.println("Expected exception: GetMePerformanceMonitoringCapabilitiesException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getHistoryPerformanceMonitoringData...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getHistoryPerformanceMonitoringData_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getHistoryPerformanceMonitoringData_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getHistoryPerformanceMonitoringData_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetHistoryPerformanceMonitoringDataRequest _getHistoryPerformanceMonitoringData_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringDataObjectsResponseType _getHistoryPerformanceMonitoringData__return = port.getHistoryPerformanceMonitoringData(_getHistoryPerformanceMonitoringData_mtopHeader, _getHistoryPerformanceMonitoringData_mtopBody);
            System.out.println("getHistoryPerformanceMonitoringData.result=" + _getHistoryPerformanceMonitoringData__return);

            System.out.println("getHistoryPerformanceMonitoringData._getHistoryPerformanceMonitoringData_mtopHeader=" + _getHistoryPerformanceMonitoringData_mtopHeader.value);
        } catch (GetHistoryPerformanceMonitoringDataException e) { 
            System.out.println("Expected exception: GetHistoryPerformanceMonitoringDataException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllCurrentPerformanceMonitoringData...");
        org.tmforum.mtop.fmw.xsd.hdr.v1.Header _getAllCurrentPerformanceMonitoringData_mtopHeaderVal = null;
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> _getAllCurrentPerformanceMonitoringData_mtopHeader = new javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header>(_getAllCurrentPerformanceMonitoringData_mtopHeaderVal);
        org.tmforum.mtop.rpm.xsd.pmr.v1.GetAllCurrentPerformanceMonitoringDataRequest _getAllCurrentPerformanceMonitoringData_mtopBody = null;
        try {
            org.tmforum.mtop.rpm.xsd.pmr.v1.MultiplePerformanceMonitoringDataObjectsResponseType _getAllCurrentPerformanceMonitoringData__return = port.getAllCurrentPerformanceMonitoringData(_getAllCurrentPerformanceMonitoringData_mtopHeader, _getAllCurrentPerformanceMonitoringData_mtopBody);
            System.out.println("getAllCurrentPerformanceMonitoringData.result=" + _getAllCurrentPerformanceMonitoringData__return);

            System.out.println("getAllCurrentPerformanceMonitoringData._getAllCurrentPerformanceMonitoringData_mtopHeader=" + _getAllCurrentPerformanceMonitoringData_mtopHeader.value);
        } catch (GetAllCurrentPerformanceMonitoringDataException e) { 
            System.out.println("Expected exception: GetAllCurrentPerformanceMonitoringDataException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
