
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.718+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllTopologicalLinksBetweenMdsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetAllTopologicalLinksBetweenMdsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksBetweenMdsException getAllTopologicalLinksBetweenMdsException;

    public GetAllTopologicalLinksBetweenMdsException() {
        super();
    }
    
    public GetAllTopologicalLinksBetweenMdsException(String message) {
        super(message);
    }
    
    public GetAllTopologicalLinksBetweenMdsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllTopologicalLinksBetweenMdsException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksBetweenMdsException getAllTopologicalLinksBetweenMdsException) {
        super(message);
        this.getAllTopologicalLinksBetweenMdsException = getAllTopologicalLinksBetweenMdsException;
    }

    public GetAllTopologicalLinksBetweenMdsException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksBetweenMdsException getAllTopologicalLinksBetweenMdsException, Throwable cause) {
        super(message, cause);
        this.getAllTopologicalLinksBetweenMdsException = getAllTopologicalLinksBetweenMdsException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksBetweenMdsException getFaultInfo() {
        return this.getAllTopologicalLinksBetweenMdsException;
    }
}
