
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.812+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllTopologicalLinksWrtOsException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetAllTopologicalLinksWrtOsException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksWrtOsException getAllTopologicalLinksWrtOsException;

    public GetAllTopologicalLinksWrtOsException() {
        super();
    }
    
    public GetAllTopologicalLinksWrtOsException(String message) {
        super(message);
    }
    
    public GetAllTopologicalLinksWrtOsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllTopologicalLinksWrtOsException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksWrtOsException getAllTopologicalLinksWrtOsException) {
        super(message);
        this.getAllTopologicalLinksWrtOsException = getAllTopologicalLinksWrtOsException;
    }

    public GetAllTopologicalLinksWrtOsException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksWrtOsException getAllTopologicalLinksWrtOsException, Throwable cause) {
        super(message, cause);
        this.getAllTopologicalLinksWrtOsException = getAllTopologicalLinksWrtOsException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksWrtOsException getFaultInfo() {
        return this.getAllTopologicalLinksWrtOsException;
    }
}
