
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.656+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllTopLevelTopologicalLinksException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetAllTopLevelTopologicalLinksException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopLevelTopologicalLinksException getAllTopLevelTopologicalLinksException;

    public GetAllTopLevelTopologicalLinksException() {
        super();
    }
    
    public GetAllTopLevelTopologicalLinksException(String message) {
        super(message);
    }
    
    public GetAllTopLevelTopologicalLinksException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllTopLevelTopologicalLinksException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopLevelTopologicalLinksException getAllTopLevelTopologicalLinksException) {
        super(message);
        this.getAllTopLevelTopologicalLinksException = getAllTopLevelTopologicalLinksException;
    }

    public GetAllTopLevelTopologicalLinksException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopLevelTopologicalLinksException getAllTopLevelTopologicalLinksException, Throwable cause) {
        super(message, cause);
        this.getAllTopLevelTopologicalLinksException = getAllTopLevelTopologicalLinksException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopLevelTopologicalLinksException getFaultInfo() {
        return this.getAllTopLevelTopologicalLinksException;
    }
}
