
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.812+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAllTopologicalLinksException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetAllTopologicalLinksException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksException getAllTopologicalLinksException;

    public GetAllTopologicalLinksException() {
        super();
    }
    
    public GetAllTopologicalLinksException(String message) {
        super(message);
    }
    
    public GetAllTopologicalLinksException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllTopologicalLinksException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksException getAllTopologicalLinksException) {
        super(message);
        this.getAllTopologicalLinksException = getAllTopologicalLinksException;
    }

    public GetAllTopologicalLinksException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksException getAllTopologicalLinksException, Throwable cause) {
        super(message, cause);
        this.getAllTopologicalLinksException = getAllTopologicalLinksException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksException getFaultInfo() {
        return this.getAllTopologicalLinksException;
    }
}
