
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.750+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getRouteAndTopologicalLinksException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetRouteAndTopologicalLinksException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetRouteAndTopologicalLinksException getRouteAndTopologicalLinksException;

    public GetRouteAndTopologicalLinksException() {
        super();
    }
    
    public GetRouteAndTopologicalLinksException(String message) {
        super(message);
    }
    
    public GetRouteAndTopologicalLinksException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetRouteAndTopologicalLinksException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetRouteAndTopologicalLinksException getRouteAndTopologicalLinksException) {
        super(message);
        this.getRouteAndTopologicalLinksException = getRouteAndTopologicalLinksException;
    }

    public GetRouteAndTopologicalLinksException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetRouteAndTopologicalLinksException getRouteAndTopologicalLinksException, Throwable cause) {
        super(message, cause);
        this.getRouteAndTopologicalLinksException = getRouteAndTopologicalLinksException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetRouteAndTopologicalLinksException getFaultInfo() {
        return this.getRouteAndTopologicalLinksException;
    }
}
