
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.718+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTopLevelTopologicalLinkException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetTopLevelTopologicalLinkException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetTopLevelTopologicalLinkException getTopLevelTopologicalLinkException;

    public GetTopLevelTopologicalLinkException() {
        super();
    }
    
    public GetTopLevelTopologicalLinkException(String message) {
        super(message);
    }
    
    public GetTopLevelTopologicalLinkException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTopLevelTopologicalLinkException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetTopLevelTopologicalLinkException getTopLevelTopologicalLinkException) {
        super(message);
        this.getTopLevelTopologicalLinkException = getTopLevelTopologicalLinkException;
    }

    public GetTopLevelTopologicalLinkException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetTopLevelTopologicalLinkException getTopLevelTopologicalLinkException, Throwable cause) {
        super(message, cause);
        this.getTopLevelTopologicalLinkException = getTopLevelTopologicalLinkException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetTopLevelTopologicalLinkException getFaultInfo() {
        return this.getTopLevelTopologicalLinkException;
    }
}
