
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.765+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTopologicalLinksIteratorException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetTopologicalLinksIteratorException extends Exception {
    
    private org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTopologicalLinksIteratorException;

    public GetTopologicalLinksIteratorException() {
        super();
    }
    
    public GetTopologicalLinksIteratorException(String message) {
        super(message);
    }
    
    public GetTopologicalLinksIteratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTopologicalLinksIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTopologicalLinksIteratorException) {
        super(message);
        this.getTopologicalLinksIteratorException = getTopologicalLinksIteratorException;
    }

    public GetTopologicalLinksIteratorException(String message, org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getTopologicalLinksIteratorException, Throwable cause) {
        super(message, cause);
        this.getTopologicalLinksIteratorException = getTopologicalLinksIteratorException;
    }

    public org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorExceptionType getFaultInfo() {
        return this.getTopologicalLinksIteratorException;
    }
}
