
package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.781+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getTopologicalLinkException", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
public class GetTopologicalLinkException extends Exception {
    
    private org.tmforum.mtop.mri.xsd.tlr.v1.GetTopologicalLinkException getTopologicalLinkException;

    public GetTopologicalLinkException() {
        super();
    }
    
    public GetTopologicalLinkException(String message) {
        super(message);
    }
    
    public GetTopologicalLinkException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTopologicalLinkException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetTopologicalLinkException getTopologicalLinkException) {
        super(message);
        this.getTopologicalLinkException = getTopologicalLinkException;
    }

    public GetTopologicalLinkException(String message, org.tmforum.mtop.mri.xsd.tlr.v1.GetTopologicalLinkException getTopologicalLinkException, Throwable cause) {
        super(message, cause);
        this.getTopologicalLinkException = getTopologicalLinkException;
    }

    public org.tmforum.mtop.mri.xsd.tlr.v1.GetTopologicalLinkException getFaultInfo() {
        return this.getTopologicalLinkException;
    }
}
