package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.859+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "TopologicalLinkRetrievalHttp", 
                  wsdlLocation = "http://192.168.189.46:9997/TopologicalLinkRetrieval?wsdl",
                  targetNamespace = "http://www.tmforum.org/mtop/mri/wsdl/tlr/v1-0") 
public class TopologicalLinkRetrievalHttp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmforum.org/mtop/mri/wsdl/tlr/v1-0", "TopologicalLinkRetrievalHttp");
    public final static QName TopologicalLinkRetrievalRPC = new QName("http://www.tmforum.org/mtop/mri/wsdl/tlr/v1-0", "TopologicalLinkRetrieval_RPC");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.189.46:9997/TopologicalLinkRetrieval?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TopologicalLinkRetrievalHttp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.189.46:9997/TopologicalLinkRetrieval?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TopologicalLinkRetrievalHttp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TopologicalLinkRetrievalHttp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TopologicalLinkRetrievalHttp() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TopologicalLinkRetrievalRPC
     */
    @WebEndpoint(name = "TopologicalLinkRetrieval_RPC")
    public TopologicalLinkRetrievalRPC getTopologicalLinkRetrievalRPC() {
        return super.getPort(TopologicalLinkRetrievalRPC, TopologicalLinkRetrievalRPC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TopologicalLinkRetrievalRPC
     */
    @WebEndpoint(name = "TopologicalLinkRetrieval_RPC")
    public TopologicalLinkRetrievalRPC getTopologicalLinkRetrievalRPC(WebServiceFeature... features) {
        return super.getPort(TopologicalLinkRetrievalRPC, TopologicalLinkRetrievalRPC.class, features);
    }

}
