package org.tmforum.mtop.mri.wsdl.tlr.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:51:55.828+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.tmforum.org/mtop/mri/wsdl/tlr/v1-0", name = "TopologicalLinkRetrieval_RPC")
@XmlSeeAlso({org.tmforum.mtop.nrf.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.hdr.v1.ObjectFactory.class, org.tmforum.mtop.mri.xsd.tlr.v1.ObjectFactory.class, org.tmforum.mtop.vs.xsd.rr.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lay.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.tnp.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.route.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.coi.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.tl.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.msg.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.gen.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.cri.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.cc.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.itu.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nrf.xsd.tpdata.v1.ObjectFactory.class, org.tmforum.mtop.fmw.xsd.nam.v1.ObjectFactory.class, org.tmforum.mtop.nra.xsd.pgp.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.com.v1.ObjectFactory.class, org.tmforum.mtop.nrb.xsd.lp.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TopologicalLinkRetrievalRPC {

    @WebResult(name = "getAllTopLevelTopologicalLinksResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllTopLevelTopologicalLinks")
    public org.tmforum.mtop.mri.xsd.tlr.v1.MultipleTlObjectsResponseType getAllTopLevelTopologicalLinks(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllTopLevelTopologicalLinksRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopLevelTopologicalLinksRequest mtopBody
    ) throws GetAllTopLevelTopologicalLinksException;

    @WebResult(name = "getTopLevelTopologicalLinkResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getTopLevelTopologicalLink")
    public org.tmforum.mtop.mri.xsd.tlr.v1.GetTopLevelTopologicalLinkResponse getTopLevelTopologicalLink(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTopLevelTopologicalLinkRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetTopLevelTopologicalLinkRequest mtopBody
    ) throws GetTopLevelTopologicalLinkException;

    @WebResult(name = "getAllTopologicalLinksBetweenMdsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllTopologicalLinksBetweenMds")
    public org.tmforum.mtop.mri.xsd.tlr.v1.MultipleTlObjectsResponseType getAllTopologicalLinksBetweenMds(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllTopologicalLinksBetweenMdsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksBetweenMdsRequest mtopBody
    ) throws GetAllTopologicalLinksBetweenMdsException;

    @WebResult(name = "getRouteAndTopologicalLinksResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getRouteAndTopologicalLinks")
    public org.tmforum.mtop.mri.xsd.tlr.v1.GetRouteAndTopologicalLinksResponse getRouteAndTopologicalLinks(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getRouteAndTopologicalLinksRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetRouteAndTopologicalLinksRequest mtopBody
    ) throws GetRouteAndTopologicalLinksException;

    @WebResult(name = "getTopologicalLinksIteratorResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getTopologicalLinksIterator")
    public org.tmforum.mtop.mri.xsd.tlr.v1.MultipleTlObjectsResponseType getTopologicalLinksIterator(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTopologicalLinksIteratorRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.fmw.xsd.msg.v1.GetAllDataIteratorRequestType mtopBody
    ) throws GetTopologicalLinksIteratorException;

    @WebResult(name = "getTopologicalLinkResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getTopologicalLink")
    public org.tmforum.mtop.mri.xsd.tlr.v1.SingleObjectResponseType getTopologicalLink(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getTopologicalLinkRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetTopologicalLinkRequest mtopBody
    ) throws GetTopologicalLinkException;

    @WebResult(name = "getAllTopologicalLinksWrtOsResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllTopologicalLinksWrtOs")
    public org.tmforum.mtop.mri.xsd.tlr.v1.MultipleTlObjectsResponseType getAllTopologicalLinksWrtOs(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllTopologicalLinksWrtOsRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksWrtOsRequest mtopBody
    ) throws GetAllTopologicalLinksWrtOsException;

    @WebResult(name = "getAllTopologicalLinksResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllTopologicalLinks")
    public org.tmforum.mtop.mri.xsd.tlr.v1.MultipleTlObjectsResponseType getAllTopologicalLinks(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllTopologicalLinksRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksRequest mtopBody
    ) throws GetAllTopologicalLinksException;

    @WebResult(name = "getAllTopologicalLinksOfFdResponse", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1", partName = "mtopBody")
    @WebMethod(action = "getAllTopologicalLinksOfFd")
    public org.tmforum.mtop.mri.xsd.tlr.v1.MultipleTlObjectsResponseType getAllTopologicalLinksOfFd(
        @WebParam(partName = "mtopHeader", mode = WebParam.Mode.INOUT, name = "header", targetNamespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", header = true)
        javax.xml.ws.Holder<org.tmforum.mtop.fmw.xsd.hdr.v1.Header> mtopHeader,
        @WebParam(partName = "mtopBody", name = "getAllTopologicalLinksOfFdRequest", targetNamespace = "http://www.tmforum.org/mtop/mri/xsd/tlr/v1")
        org.tmforum.mtop.mri.xsd.tlr.v1.GetAllTopologicalLinksOfFdRequest mtopBody
    ) throws GetAllTopologicalLinksOfFdException;
}
