package org.tmforum.mtop.rtm.wsdl.ar.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:43.109+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "AlarmRetrievalHttp", 
                  wsdlLocation = "http://192.168.189.46:9997/AlarmRetrieval?wsdl",
                  targetNamespace = "http://www.tmforum.org/mtop/rtm/wsdl/ar/v1-0") 
public class AlarmRetrievalHttp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmforum.org/mtop/rtm/wsdl/ar/v1-0", "AlarmRetrievalHttp");
    public final static QName AlarmRetrieval = new QName("http://www.tmforum.org/mtop/rtm/wsdl/ar/v1-0", "AlarmRetrieval");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.189.46:9997/AlarmRetrieval?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlarmRetrievalHttp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.189.46:9997/AlarmRetrieval?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlarmRetrievalHttp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlarmRetrievalHttp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlarmRetrievalHttp() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AlarmRetrieval
     */
    @WebEndpoint(name = "AlarmRetrieval")
    public AlarmRetrieval getAlarmRetrieval() {
        return super.getPort(AlarmRetrieval, AlarmRetrieval.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlarmRetrieval
     */
    @WebEndpoint(name = "AlarmRetrieval")
    public AlarmRetrieval getAlarmRetrieval(WebServiceFeature... features) {
        return super.getPort(AlarmRetrieval, AlarmRetrieval.class, features);
    }

}
