
package org.tmforum.mtop.rtm.wsdl.ar.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:43.015+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getAlarmAffectedServiceNamesException", targetNamespace = "http://www.tmforum.org/mtop/rtm/xsd/ar/v1")
public class GetAlarmAffectedServiceNamesException extends Exception {
    
    private org.tmforum.mtop.rtm.xsd.ar.v1.GetAlarmAffectedServiceNamesException getAlarmAffectedServiceNamesException;

    public GetAlarmAffectedServiceNamesException() {
        super();
    }
    
    public GetAlarmAffectedServiceNamesException(String message) {
        super(message);
    }
    
    public GetAlarmAffectedServiceNamesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAlarmAffectedServiceNamesException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetAlarmAffectedServiceNamesException getAlarmAffectedServiceNamesException) {
        super(message);
        this.getAlarmAffectedServiceNamesException = getAlarmAffectedServiceNamesException;
    }

    public GetAlarmAffectedServiceNamesException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetAlarmAffectedServiceNamesException getAlarmAffectedServiceNamesException, Throwable cause) {
        super(message, cause);
        this.getAlarmAffectedServiceNamesException = getAlarmAffectedServiceNamesException;
    }

    public org.tmforum.mtop.rtm.xsd.ar.v1.GetAlarmAffectedServiceNamesException getFaultInfo() {
        return this.getAlarmAffectedServiceNamesException;
    }
}
