
package org.tmforum.mtop.rtm.wsdl.ar.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:43.015+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getActiveAlarmsCountException", targetNamespace = "http://www.tmforum.org/mtop/rtm/xsd/ar/v1")
public class GetActiveAlarmsCountException extends Exception {
    
    private org.tmforum.mtop.rtm.xsd.ar.v1.GetActiveAlarmsCountException getActiveAlarmsCountException;

    public GetActiveAlarmsCountException() {
        super();
    }
    
    public GetActiveAlarmsCountException(String message) {
        super(message);
    }
    
    public GetActiveAlarmsCountException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetActiveAlarmsCountException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetActiveAlarmsCountException getActiveAlarmsCountException) {
        super(message);
        this.getActiveAlarmsCountException = getActiveAlarmsCountException;
    }

    public GetActiveAlarmsCountException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetActiveAlarmsCountException getActiveAlarmsCountException, Throwable cause) {
        super(message, cause);
        this.getActiveAlarmsCountException = getActiveAlarmsCountException;
    }

    public org.tmforum.mtop.rtm.xsd.ar.v1.GetActiveAlarmsCountException getFaultInfo() {
        return this.getActiveAlarmsCountException;
    }
}
