
package org.tmforum.mtop.rtm.wsdl.ar.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:43.062+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getSecondlyAlarmsException", targetNamespace = "http://www.tmforum.org/mtop/rtm/xsd/ar/v1")
public class GetSecondlyAlarmsException extends Exception {
    
    private org.tmforum.mtop.rtm.xsd.ar.v1.GetSecondlyAlarmsException getSecondlyAlarmsException;

    public GetSecondlyAlarmsException() {
        super();
    }
    
    public GetSecondlyAlarmsException(String message) {
        super(message);
    }
    
    public GetSecondlyAlarmsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetSecondlyAlarmsException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetSecondlyAlarmsException getSecondlyAlarmsException) {
        super(message);
        this.getSecondlyAlarmsException = getSecondlyAlarmsException;
    }

    public GetSecondlyAlarmsException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetSecondlyAlarmsException getSecondlyAlarmsException, Throwable cause) {
        super(message, cause);
        this.getSecondlyAlarmsException = getSecondlyAlarmsException;
    }

    public org.tmforum.mtop.rtm.xsd.ar.v1.GetSecondlyAlarmsException getFaultInfo() {
        return this.getSecondlyAlarmsException;
    }
}
