
package org.tmforum.mtop.rtm.wsdl.ar.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-14T13:52:43.046+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getThresholdCrossingAlertsException", targetNamespace = "http://www.tmforum.org/mtop/rtm/xsd/ar/v1")
public class GetThresholdCrossingAlertsException extends Exception {
    
    private org.tmforum.mtop.rtm.xsd.ar.v1.GetThresholdCrossingAlertsException getThresholdCrossingAlertsException;

    public GetThresholdCrossingAlertsException() {
        super();
    }
    
    public GetThresholdCrossingAlertsException(String message) {
        super(message);
    }
    
    public GetThresholdCrossingAlertsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetThresholdCrossingAlertsException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetThresholdCrossingAlertsException getThresholdCrossingAlertsException) {
        super(message);
        this.getThresholdCrossingAlertsException = getThresholdCrossingAlertsException;
    }

    public GetThresholdCrossingAlertsException(String message, org.tmforum.mtop.rtm.xsd.ar.v1.GetThresholdCrossingAlertsException getThresholdCrossingAlertsException, Throwable cause) {
        super(message, cause);
        this.getThresholdCrossingAlertsException = getThresholdCrossingAlertsException;
    }

    public org.tmforum.mtop.rtm.xsd.ar.v1.GetThresholdCrossingAlertsException getFaultInfo() {
        return this.getThresholdCrossingAlertsException;
    }
}
